// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: blackice/proto/blackice/v1/panic.proto

package blackicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PanicTier_Level int32

const (
	PanicTier_TIER_0_NORMAL            PanicTier_Level = 0 // Normal operations
	PanicTier_TIER_1_GUARDED           PanicTier_Level = 1 // Heightened monitoring, reduced thresholds for alerts
	PanicTier_TIER_2_ISOLATE_EDGE      PanicTier_Level = 2 // Isolate specific edge nodes/segments, rate limit external APIs
	PanicTier_TIER_3_REGIONAL_LOCKDOWN PanicTier_Level = 3 // Isolate entire regions, pause non-critical ingestion
	PanicTier_TIER_4_SYSTEM_BURNBACK   PanicTier_Level = 4 // Progressive rollback of data/config, activate satellite relays
	PanicTier_TIER_5_FULL_STOP         PanicTier_Level = 5 // Complete system halt, preserve forensic state, activate off-planet backup
)

// Enum value maps for PanicTier_Level.
var (
	PanicTier_Level_name = map[int32]string{
		0: "TIER_0_NORMAL",
		1: "TIER_1_GUARDED",
		2: "TIER_2_ISOLATE_EDGE",
		3: "TIER_3_REGIONAL_LOCKDOWN",
		4: "TIER_4_SYSTEM_BURNBACK",
		5: "TIER_5_FULL_STOP",
	}
	PanicTier_Level_value = map[string]int32{
		"TIER_0_NORMAL":            0,
		"TIER_1_GUARDED":           1,
		"TIER_2_ISOLATE_EDGE":      2,
		"TIER_3_REGIONAL_LOCKDOWN": 3,
		"TIER_4_SYSTEM_BURNBACK":   4,
		"TIER_5_FULL_STOP":         5,
	}
)

func (x PanicTier_Level) Enum() *PanicTier_Level {
	p := new(PanicTier_Level)
	*p = x
	return p
}

func (x PanicTier_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PanicTier_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_blackice_proto_blackice_v1_panic_proto_enumTypes[0].Descriptor()
}

func (PanicTier_Level) Type() protoreflect.EnumType {
	return &file_blackice_proto_blackice_v1_panic_proto_enumTypes[0]
}

func (x PanicTier_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PanicTier_Level.Descriptor instead.
func (PanicTier_Level) EnumDescriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{0, 0}
}

// Tiered Panic Levels as per requirements (Sec 7.3, 11)
// These levels dictate the severity of automated and manual responses.
type PanicTier struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Level       PanicTier_Level        `protobuf:"varint,1,opt,name=level,proto3,enum=blackice.v1.PanicTier_Level" json:"level,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Playbook ID associated with actions for this tier
	PlaybookId    string `protobuf:"bytes,3,opt,name=playbook_id,json=playbookId,proto3" json:"playbook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanicTier) Reset() {
	*x = PanicTier{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanicTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanicTier) ProtoMessage() {}

func (x *PanicTier) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanicTier.ProtoReflect.Descriptor instead.
func (*PanicTier) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{0}
}

func (x *PanicTier) GetLevel() PanicTier_Level {
	if x != nil {
		return x.Level
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *PanicTier) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PanicTier) GetPlaybookId() string {
	if x != nil {
		return x.PlaybookId
	}
	return ""
}

type TriggerPanicRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TargetTier            PanicTier_Level        `protobuf:"varint,1,opt,name=target_tier,json=targetTier,proto3,enum=blackice.v1.PanicTier_Level" json:"target_tier,omitempty"`
	Reason                string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	TriggeringComponentId string                 `protobuf:"bytes,3,opt,name=triggering_component_id,json=triggeringComponentId,proto3" json:"triggering_component_id,omitempty"` // ID of the component detecting the need for panic
	TriggerAttestation    *Attestation           `protobuf:"bytes,4,opt,name=trigger_attestation,json=triggerAttestation,proto3" json:"trigger_attestation,omitempty"`            // Attestation from the triggering component
	AssociatedAnomalies   []*Anomaly             `protobuf:"bytes,5,rep,name=associated_anomalies,json=associatedAnomalies,proto3" json:"associated_anomalies,omitempty"`         // Anomalies leading to this panic
	// For higher tiers, may require multi-party authorization attestations
	AuthorizationAttestations []*Attestation `protobuf:"bytes,6,rep,name=authorization_attestations,json=authorizationAttestations,proto3" json:"authorization_attestations,omitempty"`
	IncidentId                string         `protobuf:"bytes,7,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"` // Correlate with incident management systems
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TriggerPanicRequest) Reset() {
	*x = TriggerPanicRequest{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPanicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPanicRequest) ProtoMessage() {}

func (x *TriggerPanicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPanicRequest.ProtoReflect.Descriptor instead.
func (*TriggerPanicRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerPanicRequest) GetTargetTier() PanicTier_Level {
	if x != nil {
		return x.TargetTier
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *TriggerPanicRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TriggerPanicRequest) GetTriggeringComponentId() string {
	if x != nil {
		return x.TriggeringComponentId
	}
	return ""
}

func (x *TriggerPanicRequest) GetTriggerAttestation() *Attestation {
	if x != nil {
		return x.TriggerAttestation
	}
	return nil
}

func (x *TriggerPanicRequest) GetAssociatedAnomalies() []*Anomaly {
	if x != nil {
		return x.AssociatedAnomalies
	}
	return nil
}

func (x *TriggerPanicRequest) GetAuthorizationAttestations() []*Attestation {
	if x != nil {
		return x.AuthorizationAttestations
	}
	return nil
}

func (x *TriggerPanicRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

type PanicResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PanicEventId            string                 `protobuf:"bytes,2,opt,name=panic_event_id,json=panicEventId,proto3" json:"panic_event_id,omitempty"`
	CurrentTierActivated    PanicTier_Level        `protobuf:"varint,3,opt,name=current_tier_activated,json=currentTierActivated,proto3,enum=blackice.v1.PanicTier_Level" json:"current_tier_activated,omitempty"`
	ActivatedAtUnixNs       int64                  `protobuf:"varint,4,opt,name=activated_at_unix_ns,json=activatedAtUnixNs,proto3" json:"activated_at_unix_ns,omitempty"`
	LedgerEntryConfirmation *LedgerEntry           `protobuf:"bytes,5,opt,name=ledger_entry_confirmation,json=ledgerEntryConfirmation,proto3" json:"ledger_entry_confirmation,omitempty"`
	NextStepsSummary        string                 `protobuf:"bytes,6,opt,name=next_steps_summary,json=nextStepsSummary,proto3" json:"next_steps_summary,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PanicResponse) Reset() {
	*x = PanicResponse{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanicResponse) ProtoMessage() {}

func (x *PanicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanicResponse.ProtoReflect.Descriptor instead.
func (*PanicResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{2}
}

func (x *PanicResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PanicResponse) GetPanicEventId() string {
	if x != nil {
		return x.PanicEventId
	}
	return ""
}

func (x *PanicResponse) GetCurrentTierActivated() PanicTier_Level {
	if x != nil {
		return x.CurrentTierActivated
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *PanicResponse) GetActivatedAtUnixNs() int64 {
	if x != nil {
		return x.ActivatedAtUnixNs
	}
	return 0
}

func (x *PanicResponse) GetLedgerEntryConfirmation() *LedgerEntry {
	if x != nil {
		return x.LedgerEntryConfirmation
	}
	return nil
}

func (x *PanicResponse) GetNextStepsSummary() string {
	if x != nil {
		return x.NextStepsSummary
	}
	return ""
}

type GetPanicStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PanicEventId  string                 `protobuf:"bytes,1,opt,name=panic_event_id,json=panicEventId,proto3" json:"panic_event_id,omitempty"` // Optional: if empty, returns general system panic status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPanicStatusRequest) Reset() {
	*x = GetPanicStatusRequest{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPanicStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPanicStatusRequest) ProtoMessage() {}

func (x *GetPanicStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPanicStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPanicStatusRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{3}
}

func (x *GetPanicStatusRequest) GetPanicEventId() string {
	if x != nil {
		return x.PanicEventId
	}
	return ""
}

type PanicStatusResponse struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	Status             *Status                    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PanicEventId       string                     `protobuf:"bytes,2,opt,name=panic_event_id,json=panicEventId,proto3" json:"panic_event_id,omitempty"` // If a specific event is active
	CurrentSystemTier  PanicTier_Level            `protobuf:"varint,3,opt,name=current_system_tier,json=currentSystemTier,proto3,enum=blackice.v1.PanicTier_Level" json:"current_system_tier,omitempty"`
	CurrentPlaybookId  string                     `protobuf:"bytes,4,opt,name=current_playbook_id,json=currentPlaybookId,proto3" json:"current_playbook_id,omitempty"`
	ComponentStates    map[string]PanicTier_Level `protobuf:"bytes,5,rep,name=component_states,json=componentStates,proto3" json:"component_states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=blackice.v1.PanicTier_Level"` // State of various components
	LastUpdatedUnixNs  int64                      `protobuf:"varint,6,opt,name=last_updated_unix_ns,json=lastUpdatedUnixNs,proto3" json:"last_updated_unix_ns,omitempty"`
	PanicServiceHealth *NodeHealth                `protobuf:"bytes,7,opt,name=panic_service_health,json=panicServiceHealth,proto3" json:"panic_service_health,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PanicStatusResponse) Reset() {
	*x = PanicStatusResponse{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanicStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanicStatusResponse) ProtoMessage() {}

func (x *PanicStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanicStatusResponse.ProtoReflect.Descriptor instead.
func (*PanicStatusResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{4}
}

func (x *PanicStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PanicStatusResponse) GetPanicEventId() string {
	if x != nil {
		return x.PanicEventId
	}
	return ""
}

func (x *PanicStatusResponse) GetCurrentSystemTier() PanicTier_Level {
	if x != nil {
		return x.CurrentSystemTier
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *PanicStatusResponse) GetCurrentPlaybookId() string {
	if x != nil {
		return x.CurrentPlaybookId
	}
	return ""
}

func (x *PanicStatusResponse) GetComponentStates() map[string]PanicTier_Level {
	if x != nil {
		return x.ComponentStates
	}
	return nil
}

func (x *PanicStatusResponse) GetLastUpdatedUnixNs() int64 {
	if x != nil {
		return x.LastUpdatedUnixNs
	}
	return 0
}

func (x *PanicStatusResponse) GetPanicServiceHealth() *NodeHealth {
	if x != nil {
		return x.PanicServiceHealth
	}
	return nil
}

type SignalAcknowledgement struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PanicEventId         string                 `protobuf:"bytes,1,opt,name=panic_event_id,json=panicEventId,proto3" json:"panic_event_id,omitempty"`
	ComponentId          string                 `protobuf:"bytes,2,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	AcknowledgedTier     PanicTier_Level        `protobuf:"varint,3,opt,name=acknowledged_tier,json=acknowledgedTier,proto3,enum=blackice.v1.PanicTier_Level" json:"acknowledged_tier,omitempty"`
	ExecutionStatus      *Status                `protobuf:"bytes,4,opt,name=execution_status,json=executionStatus,proto3" json:"execution_status,omitempty"` // Status of executing the tier's actions
	ComponentAttestation *Attestation           `protobuf:"bytes,5,opt,name=component_attestation,json=componentAttestation,proto3" json:"component_attestation,omitempty"`
	AcknowledgedAtUnixNs int64                  `protobuf:"varint,6,opt,name=acknowledged_at_unix_ns,json=acknowledgedAtUnixNs,proto3" json:"acknowledged_at_unix_ns,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SignalAcknowledgement) Reset() {
	*x = SignalAcknowledgement{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAcknowledgement) ProtoMessage() {}

func (x *SignalAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAcknowledgement.ProtoReflect.Descriptor instead.
func (*SignalAcknowledgement) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{5}
}

func (x *SignalAcknowledgement) GetPanicEventId() string {
	if x != nil {
		return x.PanicEventId
	}
	return ""
}

func (x *SignalAcknowledgement) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *SignalAcknowledgement) GetAcknowledgedTier() PanicTier_Level {
	if x != nil {
		return x.AcknowledgedTier
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *SignalAcknowledgement) GetExecutionStatus() *Status {
	if x != nil {
		return x.ExecutionStatus
	}
	return nil
}

func (x *SignalAcknowledgement) GetComponentAttestation() *Attestation {
	if x != nil {
		return x.ComponentAttestation
	}
	return nil
}

func (x *SignalAcknowledgement) GetAcknowledgedAtUnixNs() int64 {
	if x != nil {
		return x.AcknowledgedAtUnixNs
	}
	return 0
}

type AcknowledgementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AckId         string                 `protobuf:"bytes,2,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgementResponse) Reset() {
	*x = AcknowledgementResponse{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgementResponse) ProtoMessage() {}

func (x *AcknowledgementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgementResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgementResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{6}
}

func (x *AcknowledgementResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AcknowledgementResponse) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

type EscalationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PanicEventId         string                 `protobuf:"bytes,1,opt,name=panic_event_id,json=panicEventId,proto3" json:"panic_event_id,omitempty"`
	RequestedTier        PanicTier_Level        `protobuf:"varint,2,opt,name=requested_tier,json=requestedTier,proto3,enum=blackice.v1.PanicTier_Level" json:"requested_tier,omitempty"`
	Reason               string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequesterAttestation *Attestation           `protobuf:"bytes,4,opt,name=requester_attestation,json=requesterAttestation,proto3" json:"requester_attestation,omitempty"`
	ApprovalAttestations []*Attestation         `protobuf:"bytes,5,rep,name=approval_attestations,json=approvalAttestations,proto3" json:"approval_attestations,omitempty"` // If pre-approved by some parties
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EscalationRequest) Reset() {
	*x = EscalationRequest{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscalationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscalationRequest) ProtoMessage() {}

func (x *EscalationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscalationRequest.ProtoReflect.Descriptor instead.
func (*EscalationRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{7}
}

func (x *EscalationRequest) GetPanicEventId() string {
	if x != nil {
		return x.PanicEventId
	}
	return ""
}

func (x *EscalationRequest) GetRequestedTier() PanicTier_Level {
	if x != nil {
		return x.RequestedTier
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *EscalationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EscalationRequest) GetRequesterAttestation() *Attestation {
	if x != nil {
		return x.RequesterAttestation
	}
	return nil
}

func (x *EscalationRequest) GetApprovalAttestations() []*Attestation {
	if x != nil {
		return x.ApprovalAttestations
	}
	return nil
}

type DeactivatePanicRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PanicEventId          string                 `protobuf:"bytes,1,opt,name=panic_event_id,json=panicEventId,proto3" json:"panic_event_id,omitempty"`
	ReasonForDeactivation string                 `protobuf:"bytes,2,opt,name=reason_for_deactivation,json=reasonForDeactivation,proto3" json:"reason_for_deactivation,omitempty"`
	AdminAttestation      *Attestation           `protobuf:"bytes,3,opt,name=admin_attestation,json=adminAttestation,proto3" json:"admin_attestation,omitempty"` // Requires high privilege
	// Results of post-incident review / all-clear checklist
	DeactivationChecklistResults map[string]bool `protobuf:"bytes,4,rep,name=deactivation_checklist_results,json=deactivationChecklistResults,proto3" json:"deactivation_checklist_results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DeactivatePanicRequest) Reset() {
	*x = DeactivatePanicRequest{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivatePanicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivatePanicRequest) ProtoMessage() {}

func (x *DeactivatePanicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivatePanicRequest.ProtoReflect.Descriptor instead.
func (*DeactivatePanicRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivatePanicRequest) GetPanicEventId() string {
	if x != nil {
		return x.PanicEventId
	}
	return ""
}

func (x *DeactivatePanicRequest) GetReasonForDeactivation() string {
	if x != nil {
		return x.ReasonForDeactivation
	}
	return ""
}

func (x *DeactivatePanicRequest) GetAdminAttestation() *Attestation {
	if x != nil {
		return x.AdminAttestation
	}
	return nil
}

func (x *DeactivatePanicRequest) GetDeactivationChecklistResults() map[string]bool {
	if x != nil {
		return x.DeactivationChecklistResults
	}
	return nil
}

type PanicPlaybook struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlaybookId        string                 `protobuf:"bytes,1,opt,name=playbook_id,json=playbookId,proto3" json:"playbook_id,omitempty"`
	Tier              PanicTier_Level        `protobuf:"varint,2,opt,name=tier,proto3,enum=blackice.v1.PanicTier_Level" json:"tier,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Actions           []*PlaybookAction      `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Version           int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	LastUpdatedUnixNs int64                  `protobuf:"varint,6,opt,name=last_updated_unix_ns,json=lastUpdatedUnixNs,proto3" json:"last_updated_unix_ns,omitempty"`
	UpdatedByAdminId  string                 `protobuf:"bytes,7,opt,name=updated_by_admin_id,json=updatedByAdminId,proto3" json:"updated_by_admin_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PanicPlaybook) Reset() {
	*x = PanicPlaybook{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanicPlaybook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanicPlaybook) ProtoMessage() {}

func (x *PanicPlaybook) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanicPlaybook.ProtoReflect.Descriptor instead.
func (*PanicPlaybook) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{9}
}

func (x *PanicPlaybook) GetPlaybookId() string {
	if x != nil {
		return x.PlaybookId
	}
	return ""
}

func (x *PanicPlaybook) GetTier() PanicTier_Level {
	if x != nil {
		return x.Tier
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *PanicPlaybook) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PanicPlaybook) GetActions() []*PlaybookAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PanicPlaybook) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PanicPlaybook) GetLastUpdatedUnixNs() int64 {
	if x != nil {
		return x.LastUpdatedUnixNs
	}
	return 0
}

func (x *PanicPlaybook) GetUpdatedByAdminId() string {
	if x != nil {
		return x.UpdatedByAdminId
	}
	return ""
}

type PlaybookAction struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ActionId               string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	Description            string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TargetService          string                 `protobuf:"bytes,3,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`                              // e.g., "IngestGate", "StorageService", "all"
	RpcMethodToCall        string                 `protobuf:"bytes,4,opt,name=rpc_method_to_call,json=rpcMethodToCall,proto3" json:"rpc_method_to_call,omitempty"`                    // e.g., "IsolateRegion", "ReduceThroughput"
	RequestPayloadTemplate []byte                 `protobuf:"bytes,5,opt,name=request_payload_template,json=requestPayloadTemplate,proto3" json:"request_payload_template,omitempty"` // Template for the RPC request
	ExecutionOrder         int32                  `protobuf:"varint,6,opt,name=execution_order,json=executionOrder,proto3" json:"execution_order,omitempty"`
	RequireAcknowledgement bool                   `protobuf:"varint,7,opt,name=require_acknowledgement,json=requireAcknowledgement,proto3" json:"require_acknowledgement,omitempty"`
	FallbackActionId       string                 `protobuf:"bytes,8,opt,name=fallback_action_id,json=fallbackActionId,proto3" json:"fallback_action_id,omitempty"` // If this action fails
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PlaybookAction) Reset() {
	*x = PlaybookAction{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybookAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybookAction) ProtoMessage() {}

func (x *PlaybookAction) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybookAction.ProtoReflect.Descriptor instead.
func (*PlaybookAction) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{10}
}

func (x *PlaybookAction) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *PlaybookAction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlaybookAction) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *PlaybookAction) GetRpcMethodToCall() string {
	if x != nil {
		return x.RpcMethodToCall
	}
	return ""
}

func (x *PlaybookAction) GetRequestPayloadTemplate() []byte {
	if x != nil {
		return x.RequestPayloadTemplate
	}
	return nil
}

func (x *PlaybookAction) GetExecutionOrder() int32 {
	if x != nil {
		return x.ExecutionOrder
	}
	return 0
}

func (x *PlaybookAction) GetRequireAcknowledgement() bool {
	if x != nil {
		return x.RequireAcknowledgement
	}
	return false
}

func (x *PlaybookAction) GetFallbackActionId() string {
	if x != nil {
		return x.FallbackActionId
	}
	return ""
}

type ManagePanicPolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Can update a playbook, or a specific tier's default playbook
	//
	// Types that are valid to be assigned to PolicyUpdate:
	//
	//	*ManagePanicPolicyRequest_Playbook
	//	*ManagePanicPolicyRequest_TierDefinition
	PolicyUpdate     isManagePanicPolicyRequest_PolicyUpdate `protobuf_oneof:"policy_update"`
	AdminAttestation *Attestation                            `protobuf:"bytes,3,opt,name=admin_attestation,json=adminAttestation,proto3" json:"admin_attestation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ManagePanicPolicyRequest) Reset() {
	*x = ManagePanicPolicyRequest{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagePanicPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagePanicPolicyRequest) ProtoMessage() {}

func (x *ManagePanicPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagePanicPolicyRequest.ProtoReflect.Descriptor instead.
func (*ManagePanicPolicyRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{11}
}

func (x *ManagePanicPolicyRequest) GetPolicyUpdate() isManagePanicPolicyRequest_PolicyUpdate {
	if x != nil {
		return x.PolicyUpdate
	}
	return nil
}

func (x *ManagePanicPolicyRequest) GetPlaybook() *PanicPlaybook {
	if x != nil {
		if x, ok := x.PolicyUpdate.(*ManagePanicPolicyRequest_Playbook); ok {
			return x.Playbook
		}
	}
	return nil
}

func (x *ManagePanicPolicyRequest) GetTierDefinition() *PanicTier {
	if x != nil {
		if x, ok := x.PolicyUpdate.(*ManagePanicPolicyRequest_TierDefinition); ok {
			return x.TierDefinition
		}
	}
	return nil
}

func (x *ManagePanicPolicyRequest) GetAdminAttestation() *Attestation {
	if x != nil {
		return x.AdminAttestation
	}
	return nil
}

type isManagePanicPolicyRequest_PolicyUpdate interface {
	isManagePanicPolicyRequest_PolicyUpdate()
}

type ManagePanicPolicyRequest_Playbook struct {
	Playbook *PanicPlaybook `protobuf:"bytes,1,opt,name=playbook,proto3,oneof"`
}

type ManagePanicPolicyRequest_TierDefinition struct {
	TierDefinition *PanicTier `protobuf:"bytes,2,opt,name=tier_definition,json=tierDefinition,proto3,oneof"`
}

func (*ManagePanicPolicyRequest_Playbook) isManagePanicPolicyRequest_PolicyUpdate() {}

func (*ManagePanicPolicyRequest_TierDefinition) isManagePanicPolicyRequest_PolicyUpdate() {}

type ManagePanicPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PolicyVersion string                 `protobuf:"bytes,2,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagePanicPolicyResponse) Reset() {
	*x = ManagePanicPolicyResponse{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagePanicPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagePanicPolicyResponse) ProtoMessage() {}

func (x *ManagePanicPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagePanicPolicyResponse.ProtoReflect.Descriptor instead.
func (*ManagePanicPolicyResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{12}
}

func (x *ManagePanicPolicyResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ManagePanicPolicyResponse) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type BurnbackCoordinationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PanicEventId     string                 `protobuf:"bytes,1,opt,name=panic_event_id,json=panicEventId,proto3" json:"panic_event_id,omitempty"`
	TargetTier       PanicTier_Level        `protobuf:"varint,2,opt,name=target_tier,json=targetTier,proto3,enum=blackice.v1.PanicTier_Level" json:"target_tier,omitempty"`
	AffectedRegions  []string               `protobuf:"bytes,3,rep,name=affected_regions,json=affectedRegions,proto3" json:"affected_regions,omitempty"`
	AffectedServices []string               `protobuf:"bytes,4,rep,name=affected_services,json=affectedServices,proto3" json:"affected_services,omitempty"`
	// Quorum policy for coordinated actions across regions/services
	QuorumPolicyId         string       `protobuf:"bytes,5,opt,name=quorum_policy_id,json=quorumPolicyId,proto3" json:"quorum_policy_id,omitempty"`
	CoordinatorAttestation *Attestation `protobuf:"bytes,6,opt,name=coordinator_attestation,json=coordinatorAttestation,proto3" json:"coordinator_attestation,omitempty"` // Attestation from the panic coordinator leader
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BurnbackCoordinationRequest) Reset() {
	*x = BurnbackCoordinationRequest{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnbackCoordinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnbackCoordinationRequest) ProtoMessage() {}

func (x *BurnbackCoordinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnbackCoordinationRequest.ProtoReflect.Descriptor instead.
func (*BurnbackCoordinationRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{13}
}

func (x *BurnbackCoordinationRequest) GetPanicEventId() string {
	if x != nil {
		return x.PanicEventId
	}
	return ""
}

func (x *BurnbackCoordinationRequest) GetTargetTier() PanicTier_Level {
	if x != nil {
		return x.TargetTier
	}
	return PanicTier_TIER_0_NORMAL
}

func (x *BurnbackCoordinationRequest) GetAffectedRegions() []string {
	if x != nil {
		return x.AffectedRegions
	}
	return nil
}

func (x *BurnbackCoordinationRequest) GetAffectedServices() []string {
	if x != nil {
		return x.AffectedServices
	}
	return nil
}

func (x *BurnbackCoordinationRequest) GetQuorumPolicyId() string {
	if x != nil {
		return x.QuorumPolicyId
	}
	return ""
}

func (x *BurnbackCoordinationRequest) GetCoordinatorAttestation() *Attestation {
	if x != nil {
		return x.CoordinatorAttestation
	}
	return nil
}

type BurnbackCoordinationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Decision        *QuorumDecision        `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	RegionResponses map[string]*Status     `protobuf:"bytes,3,rep,name=region_responses,json=regionResponses,proto3" json:"region_responses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Status from each region coordinator
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BurnbackCoordinationResponse) Reset() {
	*x = BurnbackCoordinationResponse{}
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnbackCoordinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnbackCoordinationResponse) ProtoMessage() {}

func (x *BurnbackCoordinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_panic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnbackCoordinationResponse.ProtoReflect.Descriptor instead.
func (*BurnbackCoordinationResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP(), []int{14}
}

func (x *BurnbackCoordinationResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BurnbackCoordinationResponse) GetDecision() *QuorumDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *BurnbackCoordinationResponse) GetRegionResponses() map[string]*Status {
	if x != nil {
		return x.RegionResponses
	}
	return nil
}

var File_blackice_proto_blackice_v1_panic_proto protoreflect.FileDescriptor

const file_blackice_proto_blackice_v1_panic_proto_rawDesc = "" +
	"\n" +
	"&blackice/proto/blackice/v1/panic.proto\x12\vblackice.v1\x1a'blackice/proto/blackice/v1/common.proto\"\x9c\x02\n" +
	"\tPanicTier\x122\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\x05level\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vplaybook_id\x18\x03 \x01(\tR\n" +
	"playbookId\"\x97\x01\n" +
	"\x05Level\x12\x11\n" +
	"\rTIER_0_NORMAL\x10\x00\x12\x12\n" +
	"\x0eTIER_1_GUARDED\x10\x01\x12\x17\n" +
	"\x13TIER_2_ISOLATE_EDGE\x10\x02\x12\x1c\n" +
	"\x18TIER_3_REGIONAL_LOCKDOWN\x10\x03\x12\x1a\n" +
	"\x16TIER_4_SYSTEM_BURNBACK\x10\x04\x12\x14\n" +
	"\x10TIER_5_FULL_STOP\x10\x05\"\xb2\x03\n" +
	"\x13TriggerPanicRequest\x12=\n" +
	"\vtarget_tier\x18\x01 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\n" +
	"targetTier\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x126\n" +
	"\x17triggering_component_id\x18\x03 \x01(\tR\x15triggeringComponentId\x12I\n" +
	"\x13trigger_attestation\x18\x04 \x01(\v2\x18.blackice.v1.AttestationR\x12triggerAttestation\x12G\n" +
	"\x14associated_anomalies\x18\x05 \x03(\v2\x14.blackice.v1.AnomalyR\x13associatedAnomalies\x12W\n" +
	"\x1aauthorization_attestations\x18\x06 \x03(\v2\x18.blackice.v1.AttestationR\x19authorizationAttestations\x12\x1f\n" +
	"\vincident_id\x18\a \x01(\tR\n" +
	"incidentId\"\xeb\x02\n" +
	"\rPanicResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12$\n" +
	"\x0epanic_event_id\x18\x02 \x01(\tR\fpanicEventId\x12R\n" +
	"\x16current_tier_activated\x18\x03 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\x14currentTierActivated\x12/\n" +
	"\x14activated_at_unix_ns\x18\x04 \x01(\x03R\x11activatedAtUnixNs\x12T\n" +
	"\x19ledger_entry_confirmation\x18\x05 \x01(\v2\x18.blackice.v1.LedgerEntryR\x17ledgerEntryConfirmation\x12,\n" +
	"\x12next_steps_summary\x18\x06 \x01(\tR\x10nextStepsSummary\"=\n" +
	"\x15GetPanicStatusRequest\x12$\n" +
	"\x0epanic_event_id\x18\x01 \x01(\tR\fpanicEventId\"\xa6\x04\n" +
	"\x13PanicStatusResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12$\n" +
	"\x0epanic_event_id\x18\x02 \x01(\tR\fpanicEventId\x12L\n" +
	"\x13current_system_tier\x18\x03 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\x11currentSystemTier\x12.\n" +
	"\x13current_playbook_id\x18\x04 \x01(\tR\x11currentPlaybookId\x12`\n" +
	"\x10component_states\x18\x05 \x03(\v25.blackice.v1.PanicStatusResponse.ComponentStatesEntryR\x0fcomponentStates\x12/\n" +
	"\x14last_updated_unix_ns\x18\x06 \x01(\x03R\x11lastUpdatedUnixNs\x12I\n" +
	"\x14panic_service_health\x18\a \x01(\v2\x17.blackice.v1.NodeHealthR\x12panicServiceHealth\x1a`\n" +
	"\x14ComponentStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\x05value:\x028\x01\"\xf1\x02\n" +
	"\x15SignalAcknowledgement\x12$\n" +
	"\x0epanic_event_id\x18\x01 \x01(\tR\fpanicEventId\x12!\n" +
	"\fcomponent_id\x18\x02 \x01(\tR\vcomponentId\x12I\n" +
	"\x11acknowledged_tier\x18\x03 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\x10acknowledgedTier\x12>\n" +
	"\x10execution_status\x18\x04 \x01(\v2\x13.blackice.v1.StatusR\x0fexecutionStatus\x12M\n" +
	"\x15component_attestation\x18\x05 \x01(\v2\x18.blackice.v1.AttestationR\x14componentAttestation\x125\n" +
	"\x17acknowledged_at_unix_ns\x18\x06 \x01(\x03R\x14acknowledgedAtUnixNs\"]\n" +
	"\x17AcknowledgementResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12\x15\n" +
	"\x06ack_id\x18\x02 \x01(\tR\x05ackId\"\xb4\x02\n" +
	"\x11EscalationRequest\x12$\n" +
	"\x0epanic_event_id\x18\x01 \x01(\tR\fpanicEventId\x12C\n" +
	"\x0erequested_tier\x18\x02 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\rrequestedTier\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12M\n" +
	"\x15requester_attestation\x18\x04 \x01(\v2\x18.blackice.v1.AttestationR\x14requesterAttestation\x12M\n" +
	"\x15approval_attestations\x18\x05 \x03(\v2\x18.blackice.v1.AttestationR\x14approvalAttestations\"\x9c\x03\n" +
	"\x16DeactivatePanicRequest\x12$\n" +
	"\x0epanic_event_id\x18\x01 \x01(\tR\fpanicEventId\x126\n" +
	"\x17reason_for_deactivation\x18\x02 \x01(\tR\x15reasonForDeactivation\x12E\n" +
	"\x11admin_attestation\x18\x03 \x01(\v2\x18.blackice.v1.AttestationR\x10adminAttestation\x12\x8b\x01\n" +
	"\x1edeactivation_checklist_results\x18\x04 \x03(\v2E.blackice.v1.DeactivatePanicRequest.DeactivationChecklistResultsEntryR\x1cdeactivationChecklistResults\x1aO\n" +
	"!DeactivationChecklistResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xb5\x02\n" +
	"\rPanicPlaybook\x12\x1f\n" +
	"\vplaybook_id\x18\x01 \x01(\tR\n" +
	"playbookId\x120\n" +
	"\x04tier\x18\x02 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\x04tier\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\aactions\x18\x04 \x03(\v2\x1b.blackice.v1.PlaybookActionR\aactions\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12/\n" +
	"\x14last_updated_unix_ns\x18\x06 \x01(\x03R\x11lastUpdatedUnixNs\x12-\n" +
	"\x13updated_by_admin_id\x18\a \x01(\tR\x10updatedByAdminId\"\xed\x02\n" +
	"\x0ePlaybookAction\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\x0etarget_service\x18\x03 \x01(\tR\rtargetService\x12+\n" +
	"\x12rpc_method_to_call\x18\x04 \x01(\tR\x0frpcMethodToCall\x128\n" +
	"\x18request_payload_template\x18\x05 \x01(\fR\x16requestPayloadTemplate\x12'\n" +
	"\x0fexecution_order\x18\x06 \x01(\x05R\x0eexecutionOrder\x127\n" +
	"\x17require_acknowledgement\x18\a \x01(\bR\x16requireAcknowledgement\x12,\n" +
	"\x12fallback_action_id\x18\b \x01(\tR\x10fallbackActionId\"\xef\x01\n" +
	"\x18ManagePanicPolicyRequest\x128\n" +
	"\bplaybook\x18\x01 \x01(\v2\x1a.blackice.v1.PanicPlaybookH\x00R\bplaybook\x12A\n" +
	"\x0ftier_definition\x18\x02 \x01(\v2\x16.blackice.v1.PanicTierH\x00R\x0etierDefinition\x12E\n" +
	"\x11admin_attestation\x18\x03 \x01(\v2\x18.blackice.v1.AttestationR\x10adminAttestationB\x0f\n" +
	"\rpolicy_update\"o\n" +
	"\x19ManagePanicPolicyResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12%\n" +
	"\x0epolicy_version\x18\x02 \x01(\tR\rpolicyVersion\"\xd7\x02\n" +
	"\x1bBurnbackCoordinationRequest\x12$\n" +
	"\x0epanic_event_id\x18\x01 \x01(\tR\fpanicEventId\x12=\n" +
	"\vtarget_tier\x18\x02 \x01(\x0e2\x1c.blackice.v1.PanicTier.LevelR\n" +
	"targetTier\x12)\n" +
	"\x10affected_regions\x18\x03 \x03(\tR\x0faffectedRegions\x12+\n" +
	"\x11affected_services\x18\x04 \x03(\tR\x10affectedServices\x12(\n" +
	"\x10quorum_policy_id\x18\x05 \x01(\tR\x0equorumPolicyId\x12Q\n" +
	"\x17coordinator_attestation\x18\x06 \x01(\v2\x18.blackice.v1.AttestationR\x16coordinatorAttestation\"\xc8\x02\n" +
	"\x1cBurnbackCoordinationResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x127\n" +
	"\bdecision\x18\x02 \x01(\v2\x1b.blackice.v1.QuorumDecisionR\bdecision\x12i\n" +
	"\x10region_responses\x18\x03 \x03(\v2>.blackice.v1.BurnbackCoordinationResponse.RegionResponsesEntryR\x0fregionResponses\x1aW\n" +
	"\x14RegionResponsesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.blackice.v1.StatusR\x05value:\x028\x012\x87\x05\n" +
	"\fPanicService\x12L\n" +
	"\fTriggerPanic\x12 .blackice.v1.TriggerPanicRequest\x1a\x1a.blackice.v1.PanicResponse\x12V\n" +
	"\x0eGetPanicStatus\x12\".blackice.v1.GetPanicStatusRequest\x1a .blackice.v1.PanicStatusResponse\x12]\n" +
	"\x11AcknowledgeSignal\x12\".blackice.v1.SignalAcknowledgement\x1a$.blackice.v1.AcknowledgementResponse\x12O\n" +
	"\x11RequestEscalation\x12\x1e.blackice.v1.EscalationRequest\x1a\x1a.blackice.v1.PanicResponse\x12R\n" +
	"\x0fDeactivatePanic\x12#.blackice.v1.DeactivatePanicRequest\x1a\x1a.blackice.v1.PanicResponse\x12b\n" +
	"\x11ManagePanicPolicy\x12%.blackice.v1.ManagePanicPolicyRequest\x1a&.blackice.v1.ManagePanicPolicyResponse\x12i\n" +
	"\x12CoordinateBurnback\x12(.blackice.v1.BurnbackCoordinationRequest\x1a).blackice.v1.BurnbackCoordinationResponseB7Z5github.com/TFMV/blackice/proto/blackice/v1;blackicev1b\x06proto3"

var (
	file_blackice_proto_blackice_v1_panic_proto_rawDescOnce sync.Once
	file_blackice_proto_blackice_v1_panic_proto_rawDescData []byte
)

func file_blackice_proto_blackice_v1_panic_proto_rawDescGZIP() []byte {
	file_blackice_proto_blackice_v1_panic_proto_rawDescOnce.Do(func() {
		file_blackice_proto_blackice_v1_panic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blackice_proto_blackice_v1_panic_proto_rawDesc), len(file_blackice_proto_blackice_v1_panic_proto_rawDesc)))
	})
	return file_blackice_proto_blackice_v1_panic_proto_rawDescData
}

var file_blackice_proto_blackice_v1_panic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blackice_proto_blackice_v1_panic_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_blackice_proto_blackice_v1_panic_proto_goTypes = []any{
	(PanicTier_Level)(0),                 // 0: blackice.v1.PanicTier.Level
	(*PanicTier)(nil),                    // 1: blackice.v1.PanicTier
	(*TriggerPanicRequest)(nil),          // 2: blackice.v1.TriggerPanicRequest
	(*PanicResponse)(nil),                // 3: blackice.v1.PanicResponse
	(*GetPanicStatusRequest)(nil),        // 4: blackice.v1.GetPanicStatusRequest
	(*PanicStatusResponse)(nil),          // 5: blackice.v1.PanicStatusResponse
	(*SignalAcknowledgement)(nil),        // 6: blackice.v1.SignalAcknowledgement
	(*AcknowledgementResponse)(nil),      // 7: blackice.v1.AcknowledgementResponse
	(*EscalationRequest)(nil),            // 8: blackice.v1.EscalationRequest
	(*DeactivatePanicRequest)(nil),       // 9: blackice.v1.DeactivatePanicRequest
	(*PanicPlaybook)(nil),                // 10: blackice.v1.PanicPlaybook
	(*PlaybookAction)(nil),               // 11: blackice.v1.PlaybookAction
	(*ManagePanicPolicyRequest)(nil),     // 12: blackice.v1.ManagePanicPolicyRequest
	(*ManagePanicPolicyResponse)(nil),    // 13: blackice.v1.ManagePanicPolicyResponse
	(*BurnbackCoordinationRequest)(nil),  // 14: blackice.v1.BurnbackCoordinationRequest
	(*BurnbackCoordinationResponse)(nil), // 15: blackice.v1.BurnbackCoordinationResponse
	nil,                                  // 16: blackice.v1.PanicStatusResponse.ComponentStatesEntry
	nil,                                  // 17: blackice.v1.DeactivatePanicRequest.DeactivationChecklistResultsEntry
	nil,                                  // 18: blackice.v1.BurnbackCoordinationResponse.RegionResponsesEntry
	(*Attestation)(nil),                  // 19: blackice.v1.Attestation
	(*Anomaly)(nil),                      // 20: blackice.v1.Anomaly
	(*Status)(nil),                       // 21: blackice.v1.Status
	(*LedgerEntry)(nil),                  // 22: blackice.v1.LedgerEntry
	(*NodeHealth)(nil),                   // 23: blackice.v1.NodeHealth
	(*QuorumDecision)(nil),               // 24: blackice.v1.QuorumDecision
}
var file_blackice_proto_blackice_v1_panic_proto_depIdxs = []int32{
	0,  // 0: blackice.v1.PanicTier.level:type_name -> blackice.v1.PanicTier.Level
	0,  // 1: blackice.v1.TriggerPanicRequest.target_tier:type_name -> blackice.v1.PanicTier.Level
	19, // 2: blackice.v1.TriggerPanicRequest.trigger_attestation:type_name -> blackice.v1.Attestation
	20, // 3: blackice.v1.TriggerPanicRequest.associated_anomalies:type_name -> blackice.v1.Anomaly
	19, // 4: blackice.v1.TriggerPanicRequest.authorization_attestations:type_name -> blackice.v1.Attestation
	21, // 5: blackice.v1.PanicResponse.status:type_name -> blackice.v1.Status
	0,  // 6: blackice.v1.PanicResponse.current_tier_activated:type_name -> blackice.v1.PanicTier.Level
	22, // 7: blackice.v1.PanicResponse.ledger_entry_confirmation:type_name -> blackice.v1.LedgerEntry
	21, // 8: blackice.v1.PanicStatusResponse.status:type_name -> blackice.v1.Status
	0,  // 9: blackice.v1.PanicStatusResponse.current_system_tier:type_name -> blackice.v1.PanicTier.Level
	16, // 10: blackice.v1.PanicStatusResponse.component_states:type_name -> blackice.v1.PanicStatusResponse.ComponentStatesEntry
	23, // 11: blackice.v1.PanicStatusResponse.panic_service_health:type_name -> blackice.v1.NodeHealth
	0,  // 12: blackice.v1.SignalAcknowledgement.acknowledged_tier:type_name -> blackice.v1.PanicTier.Level
	21, // 13: blackice.v1.SignalAcknowledgement.execution_status:type_name -> blackice.v1.Status
	19, // 14: blackice.v1.SignalAcknowledgement.component_attestation:type_name -> blackice.v1.Attestation
	21, // 15: blackice.v1.AcknowledgementResponse.status:type_name -> blackice.v1.Status
	0,  // 16: blackice.v1.EscalationRequest.requested_tier:type_name -> blackice.v1.PanicTier.Level
	19, // 17: blackice.v1.EscalationRequest.requester_attestation:type_name -> blackice.v1.Attestation
	19, // 18: blackice.v1.EscalationRequest.approval_attestations:type_name -> blackice.v1.Attestation
	19, // 19: blackice.v1.DeactivatePanicRequest.admin_attestation:type_name -> blackice.v1.Attestation
	17, // 20: blackice.v1.DeactivatePanicRequest.deactivation_checklist_results:type_name -> blackice.v1.DeactivatePanicRequest.DeactivationChecklistResultsEntry
	0,  // 21: blackice.v1.PanicPlaybook.tier:type_name -> blackice.v1.PanicTier.Level
	11, // 22: blackice.v1.PanicPlaybook.actions:type_name -> blackice.v1.PlaybookAction
	10, // 23: blackice.v1.ManagePanicPolicyRequest.playbook:type_name -> blackice.v1.PanicPlaybook
	1,  // 24: blackice.v1.ManagePanicPolicyRequest.tier_definition:type_name -> blackice.v1.PanicTier
	19, // 25: blackice.v1.ManagePanicPolicyRequest.admin_attestation:type_name -> blackice.v1.Attestation
	21, // 26: blackice.v1.ManagePanicPolicyResponse.status:type_name -> blackice.v1.Status
	0,  // 27: blackice.v1.BurnbackCoordinationRequest.target_tier:type_name -> blackice.v1.PanicTier.Level
	19, // 28: blackice.v1.BurnbackCoordinationRequest.coordinator_attestation:type_name -> blackice.v1.Attestation
	21, // 29: blackice.v1.BurnbackCoordinationResponse.status:type_name -> blackice.v1.Status
	24, // 30: blackice.v1.BurnbackCoordinationResponse.decision:type_name -> blackice.v1.QuorumDecision
	18, // 31: blackice.v1.BurnbackCoordinationResponse.region_responses:type_name -> blackice.v1.BurnbackCoordinationResponse.RegionResponsesEntry
	0,  // 32: blackice.v1.PanicStatusResponse.ComponentStatesEntry.value:type_name -> blackice.v1.PanicTier.Level
	21, // 33: blackice.v1.BurnbackCoordinationResponse.RegionResponsesEntry.value:type_name -> blackice.v1.Status
	2,  // 34: blackice.v1.PanicService.TriggerPanic:input_type -> blackice.v1.TriggerPanicRequest
	4,  // 35: blackice.v1.PanicService.GetPanicStatus:input_type -> blackice.v1.GetPanicStatusRequest
	6,  // 36: blackice.v1.PanicService.AcknowledgeSignal:input_type -> blackice.v1.SignalAcknowledgement
	8,  // 37: blackice.v1.PanicService.RequestEscalation:input_type -> blackice.v1.EscalationRequest
	9,  // 38: blackice.v1.PanicService.DeactivatePanic:input_type -> blackice.v1.DeactivatePanicRequest
	12, // 39: blackice.v1.PanicService.ManagePanicPolicy:input_type -> blackice.v1.ManagePanicPolicyRequest
	14, // 40: blackice.v1.PanicService.CoordinateBurnback:input_type -> blackice.v1.BurnbackCoordinationRequest
	3,  // 41: blackice.v1.PanicService.TriggerPanic:output_type -> blackice.v1.PanicResponse
	5,  // 42: blackice.v1.PanicService.GetPanicStatus:output_type -> blackice.v1.PanicStatusResponse
	7,  // 43: blackice.v1.PanicService.AcknowledgeSignal:output_type -> blackice.v1.AcknowledgementResponse
	3,  // 44: blackice.v1.PanicService.RequestEscalation:output_type -> blackice.v1.PanicResponse
	3,  // 45: blackice.v1.PanicService.DeactivatePanic:output_type -> blackice.v1.PanicResponse
	13, // 46: blackice.v1.PanicService.ManagePanicPolicy:output_type -> blackice.v1.ManagePanicPolicyResponse
	15, // 47: blackice.v1.PanicService.CoordinateBurnback:output_type -> blackice.v1.BurnbackCoordinationResponse
	41, // [41:48] is the sub-list for method output_type
	34, // [34:41] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_blackice_proto_blackice_v1_panic_proto_init() }
func file_blackice_proto_blackice_v1_panic_proto_init() {
	if File_blackice_proto_blackice_v1_panic_proto != nil {
		return
	}
	file_blackice_proto_blackice_v1_common_proto_init()
	file_blackice_proto_blackice_v1_panic_proto_msgTypes[11].OneofWrappers = []any{
		(*ManagePanicPolicyRequest_Playbook)(nil),
		(*ManagePanicPolicyRequest_TierDefinition)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blackice_proto_blackice_v1_panic_proto_rawDesc), len(file_blackice_proto_blackice_v1_panic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blackice_proto_blackice_v1_panic_proto_goTypes,
		DependencyIndexes: file_blackice_proto_blackice_v1_panic_proto_depIdxs,
		EnumInfos:         file_blackice_proto_blackice_v1_panic_proto_enumTypes,
		MessageInfos:      file_blackice_proto_blackice_v1_panic_proto_msgTypes,
	}.Build()
	File_blackice_proto_blackice_v1_panic_proto = out.File
	file_blackice_proto_blackice_v1_panic_proto_goTypes = nil
	file_blackice_proto_blackice_v1_panic_proto_depIdxs = nil
}
