// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: blackice/proto/blackice/v1/resilience.proto

package blackicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardMetadata_ShardHealthStatus int32

const (
	ShardMetadata_UNKNOWN        ShardMetadata_ShardHealthStatus = 0
	ShardMetadata_HEALTHY        ShardMetadata_ShardHealthStatus = 1
	ShardMetadata_UNREACHABLE    ShardMetadata_ShardHealthStatus = 2
	ShardMetadata_CORRUPTED      ShardMetadata_ShardHealthStatus = 3
	ShardMetadata_PENDING_REPAIR ShardMetadata_ShardHealthStatus = 4
)

// Enum value maps for ShardMetadata_ShardHealthStatus.
var (
	ShardMetadata_ShardHealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNREACHABLE",
		3: "CORRUPTED",
		4: "PENDING_REPAIR",
	}
	ShardMetadata_ShardHealthStatus_value = map[string]int32{
		"UNKNOWN":        0,
		"HEALTHY":        1,
		"UNREACHABLE":    2,
		"CORRUPTED":      3,
		"PENDING_REPAIR": 4,
	}
)

func (x ShardMetadata_ShardHealthStatus) Enum() *ShardMetadata_ShardHealthStatus {
	p := new(ShardMetadata_ShardHealthStatus)
	*p = x
	return p
}

func (x ShardMetadata_ShardHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardMetadata_ShardHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blackice_proto_blackice_v1_resilience_proto_enumTypes[0].Descriptor()
}

func (ShardMetadata_ShardHealthStatus) Type() protoreflect.EnumType {
	return &file_blackice_proto_blackice_v1_resilience_proto_enumTypes[0]
}

func (x ShardMetadata_ShardHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardMetadata_ShardHealthStatus.Descriptor instead.
func (ShardMetadata_ShardHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{0, 0}
}

type ObjectMetadata_ObjectHealthStatus int32

const (
	ObjectMetadata_HEALTH_UNKNOWN       ObjectMetadata_ObjectHealthStatus = 0
	ObjectMetadata_HEALTH_OPTIMAL       ObjectMetadata_ObjectHealthStatus = 1 // All shards healthy, redundancy goals met
	ObjectMetadata_HEALTH_DEGRADED      ObjectMetadata_ObjectHealthStatus = 2 // Reconstructable, but some shards unhealthy or redundancy low
	ObjectMetadata_HEALTH_AT_RISK       ObjectMetadata_ObjectHealthStatus = 3 // Barely reconstructable, immediate repair needed
	ObjectMetadata_HEALTH_UNRECOVERABLE ObjectMetadata_ObjectHealthStatus = 4 // Data loss has occurred
)

// Enum value maps for ObjectMetadata_ObjectHealthStatus.
var (
	ObjectMetadata_ObjectHealthStatus_name = map[int32]string{
		0: "HEALTH_UNKNOWN",
		1: "HEALTH_OPTIMAL",
		2: "HEALTH_DEGRADED",
		3: "HEALTH_AT_RISK",
		4: "HEALTH_UNRECOVERABLE",
	}
	ObjectMetadata_ObjectHealthStatus_value = map[string]int32{
		"HEALTH_UNKNOWN":       0,
		"HEALTH_OPTIMAL":       1,
		"HEALTH_DEGRADED":      2,
		"HEALTH_AT_RISK":       3,
		"HEALTH_UNRECOVERABLE": 4,
	}
)

func (x ObjectMetadata_ObjectHealthStatus) Enum() *ObjectMetadata_ObjectHealthStatus {
	p := new(ObjectMetadata_ObjectHealthStatus)
	*p = x
	return p
}

func (x ObjectMetadata_ObjectHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectMetadata_ObjectHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blackice_proto_blackice_v1_resilience_proto_enumTypes[1].Descriptor()
}

func (ObjectMetadata_ObjectHealthStatus) Type() protoreflect.EnumType {
	return &file_blackice_proto_blackice_v1_resilience_proto_enumTypes[1]
}

func (x ObjectMetadata_ObjectHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectMetadata_ObjectHealthStatus.Descriptor instead.
func (ObjectMetadata_ObjectHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{1, 0}
}

type ShardingPolicy_ShardingAlgorithm int32

const (
	ShardingPolicy_REED_SOLOMON               ShardingPolicy_ShardingAlgorithm = 0
	ShardingPolicy_SHAMIR_SECRET_SHARING      ShardingPolicy_ShardingAlgorithm = 1
	ShardingPolicy_HYBRID_REED_SOLOMON_SHAMIR ShardingPolicy_ShardingAlgorithm = 2
)

// Enum value maps for ShardingPolicy_ShardingAlgorithm.
var (
	ShardingPolicy_ShardingAlgorithm_name = map[int32]string{
		0: "REED_SOLOMON",
		1: "SHAMIR_SECRET_SHARING",
		2: "HYBRID_REED_SOLOMON_SHAMIR",
	}
	ShardingPolicy_ShardingAlgorithm_value = map[string]int32{
		"REED_SOLOMON":               0,
		"SHAMIR_SECRET_SHARING":      1,
		"HYBRID_REED_SOLOMON_SHAMIR": 2,
	}
)

func (x ShardingPolicy_ShardingAlgorithm) Enum() *ShardingPolicy_ShardingAlgorithm {
	p := new(ShardingPolicy_ShardingAlgorithm)
	*p = x
	return p
}

func (x ShardingPolicy_ShardingAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardingPolicy_ShardingAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_blackice_proto_blackice_v1_resilience_proto_enumTypes[2].Descriptor()
}

func (ShardingPolicy_ShardingAlgorithm) Type() protoreflect.EnumType {
	return &file_blackice_proto_blackice_v1_resilience_proto_enumTypes[2]
}

func (x ShardingPolicy_ShardingAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardingPolicy_ShardingAlgorithm.Descriptor instead.
func (ShardingPolicy_ShardingAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{3, 0}
}

type PlacementPolicy_Strategy int32

const (
	PlacementPolicy_GEO_DIVERSE_REGIONS PlacementPolicy_Strategy = 0
	PlacementPolicy_PROVIDER_DIVERSE    PlacementPolicy_Strategy = 1
	PlacementPolicy_LOW_LATENCY_ACCESS  PlacementPolicy_Strategy = 2 // More can be added
)

// Enum value maps for PlacementPolicy_Strategy.
var (
	PlacementPolicy_Strategy_name = map[int32]string{
		0: "GEO_DIVERSE_REGIONS",
		1: "PROVIDER_DIVERSE",
		2: "LOW_LATENCY_ACCESS",
	}
	PlacementPolicy_Strategy_value = map[string]int32{
		"GEO_DIVERSE_REGIONS": 0,
		"PROVIDER_DIVERSE":    1,
		"LOW_LATENCY_ACCESS":  2,
	}
)

func (x PlacementPolicy_Strategy) Enum() *PlacementPolicy_Strategy {
	p := new(PlacementPolicy_Strategy)
	*p = x
	return p
}

func (x PlacementPolicy_Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlacementPolicy_Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_blackice_proto_blackice_v1_resilience_proto_enumTypes[3].Descriptor()
}

func (PlacementPolicy_Strategy) Type() protoreflect.EnumType {
	return &file_blackice_proto_blackice_v1_resilience_proto_enumTypes[3]
}

func (x PlacementPolicy_Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlacementPolicy_Strategy.Descriptor instead.
func (PlacementPolicy_Strategy) EnumDescriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{14, 0}
}

type ShardMetadata struct {
	state                protoimpl.MessageState          `protogen:"open.v1"`
	ShardId              string                          `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	StorageNodeId        string                          `protobuf:"bytes,2,opt,name=storage_node_id,json=storageNodeId,proto3" json:"storage_node_id,omitempty"`             // ID of the node holding this shard (e.g., Storj node ID)
	StorageProvider      string                          `protobuf:"bytes,3,opt,name=storage_provider,json=storageProvider,proto3" json:"storage_provider,omitempty"`         // e.g., "Storj", "IPFS", "FileSystem"
	ShardLocationHint    string                          `protobuf:"bytes,4,opt,name=shard_location_hint,json=shardLocationHint,proto3" json:"shard_location_hint,omitempty"` // e.g., IPFS CID, Storj segment path
	SizeBytes            int64                           `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IntegrityAttestation *Attestation                    `protobuf:"bytes,6,opt,name=integrity_attestation,json=integrityAttestation,proto3" json:"integrity_attestation,omitempty"` // Attestation from the storage node for this shard
	StoredAtUnixNs       int64                           `protobuf:"varint,7,opt,name=stored_at_unix_ns,json=storedAtUnixNs,proto3" json:"stored_at_unix_ns,omitempty"`
	HealthStatus         ShardMetadata_ShardHealthStatus `protobuf:"varint,8,opt,name=health_status,json=healthStatus,proto3,enum=blackice.v1.ShardMetadata_ShardHealthStatus" json:"health_status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ShardMetadata) Reset() {
	*x = ShardMetadata{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMetadata) ProtoMessage() {}

func (x *ShardMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMetadata.ProtoReflect.Descriptor instead.
func (*ShardMetadata) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{0}
}

func (x *ShardMetadata) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardMetadata) GetStorageNodeId() string {
	if x != nil {
		return x.StorageNodeId
	}
	return ""
}

func (x *ShardMetadata) GetStorageProvider() string {
	if x != nil {
		return x.StorageProvider
	}
	return ""
}

func (x *ShardMetadata) GetShardLocationHint() string {
	if x != nil {
		return x.ShardLocationHint
	}
	return ""
}

func (x *ShardMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ShardMetadata) GetIntegrityAttestation() *Attestation {
	if x != nil {
		return x.IntegrityAttestation
	}
	return nil
}

func (x *ShardMetadata) GetStoredAtUnixNs() int64 {
	if x != nil {
		return x.StoredAtUnixNs
	}
	return 0
}

func (x *ShardMetadata) GetHealthStatus() ShardMetadata_ShardHealthStatus {
	if x != nil {
		return x.HealthStatus
	}
	return ShardMetadata_UNKNOWN
}

type ObjectMetadata struct {
	state                     protoimpl.MessageState            `protogen:"open.v1"`
	ObjectId                  string                            `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"` // Unique ID for the original object
	OriginalSizeBytes         int64                             `protobuf:"varint,2,opt,name=original_size_bytes,json=originalSizeBytes,proto3" json:"original_size_bytes,omitempty"`
	ContentType               string                            `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	UserMetadata              map[string]string                 `protobuf:"bytes,4,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EncryptionMetadata        *EncryptionMetadata               `protobuf:"bytes,5,opt,name=encryption_metadata,json=encryptionMetadata,proto3" json:"encryption_metadata,omitempty"`
	ShardingPolicyUsed        *ShardingPolicy                   `protobuf:"bytes,6,opt,name=sharding_policy_used,json=shardingPolicyUsed,proto3" json:"sharding_policy_used,omitempty"`
	Shards                    []*ShardMetadata                  `protobuf:"bytes,7,rep,name=shards,proto3" json:"shards,omitempty"`
	CreatedAtUnixNs           int64                             `protobuf:"varint,8,opt,name=created_at_unix_ns,json=createdAtUnixNs,proto3" json:"created_at_unix_ns,omitempty"`
	LastAccessedUnixNs        int64                             `protobuf:"varint,9,opt,name=last_accessed_unix_ns,json=lastAccessedUnixNs,proto3" json:"last_accessed_unix_ns,omitempty"`
	LastRepairedAtUnixNs      int64                             `protobuf:"varint,10,opt,name=last_repaired_at_unix_ns,json=lastRepairedAtUnixNs,proto3" json:"last_repaired_at_unix_ns,omitempty"`
	ObjectCreationAttestation *Attestation                      `protobuf:"bytes,11,opt,name=object_creation_attestation,json=objectCreationAttestation,proto3" json:"object_creation_attestation,omitempty"` // Attestation of the object's initial secure storage
	OverallHealth             ObjectMetadata_ObjectHealthStatus `protobuf:"varint,12,opt,name=overall_health,json=overallHealth,proto3,enum=blackice.v1.ObjectMetadata_ObjectHealthStatus" json:"overall_health,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ObjectMetadata) Reset() {
	*x = ObjectMetadata{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMetadata) ProtoMessage() {}

func (x *ObjectMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMetadata.ProtoReflect.Descriptor instead.
func (*ObjectMetadata) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectMetadata) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ObjectMetadata) GetOriginalSizeBytes() int64 {
	if x != nil {
		return x.OriginalSizeBytes
	}
	return 0
}

func (x *ObjectMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectMetadata) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *ObjectMetadata) GetEncryptionMetadata() *EncryptionMetadata {
	if x != nil {
		return x.EncryptionMetadata
	}
	return nil
}

func (x *ObjectMetadata) GetShardingPolicyUsed() *ShardingPolicy {
	if x != nil {
		return x.ShardingPolicyUsed
	}
	return nil
}

func (x *ObjectMetadata) GetShards() []*ShardMetadata {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *ObjectMetadata) GetCreatedAtUnixNs() int64 {
	if x != nil {
		return x.CreatedAtUnixNs
	}
	return 0
}

func (x *ObjectMetadata) GetLastAccessedUnixNs() int64 {
	if x != nil {
		return x.LastAccessedUnixNs
	}
	return 0
}

func (x *ObjectMetadata) GetLastRepairedAtUnixNs() int64 {
	if x != nil {
		return x.LastRepairedAtUnixNs
	}
	return 0
}

func (x *ObjectMetadata) GetObjectCreationAttestation() *Attestation {
	if x != nil {
		return x.ObjectCreationAttestation
	}
	return nil
}

func (x *ObjectMetadata) GetOverallHealth() ObjectMetadata_ObjectHealthStatus {
	if x != nil {
		return x.OverallHealth
	}
	return ObjectMetadata_HEALTH_UNKNOWN
}

type EncryptionMetadata struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	MasterKeyId                 string                 `protobuf:"bytes,1,opt,name=master_key_id,json=masterKeyId,proto3" json:"master_key_id,omitempty"`                                  // Reference to the master encryption key
	EncryptedDataKey            []byte                 `protobuf:"bytes,2,opt,name=encrypted_data_key,json=encryptedDataKey,proto3" json:"encrypted_data_key,omitempty"`                   // Data encryption key, encrypted with master key
	KeyEncryptionAlgorithm      string                 `protobuf:"bytes,3,opt,name=key_encryption_algorithm,json=keyEncryptionAlgorithm,proto3" json:"key_encryption_algorithm,omitempty"` // e.g., "AES-GCM-SIV"
	NonceOrIv                   []byte                 `protobuf:"bytes,4,opt,name=nonce_or_iv,json=nonceOrIv,proto3" json:"nonce_or_iv,omitempty"`
	AdditionalAuthenticatedData map[string]string      `protobuf:"bytes,5,rep,name=additional_authenticated_data,json=additionalAuthenticatedData,proto3" json:"additional_authenticated_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *EncryptionMetadata) Reset() {
	*x = EncryptionMetadata{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionMetadata) ProtoMessage() {}

func (x *EncryptionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionMetadata.ProtoReflect.Descriptor instead.
func (*EncryptionMetadata) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptionMetadata) GetMasterKeyId() string {
	if x != nil {
		return x.MasterKeyId
	}
	return ""
}

func (x *EncryptionMetadata) GetEncryptedDataKey() []byte {
	if x != nil {
		return x.EncryptedDataKey
	}
	return nil
}

func (x *EncryptionMetadata) GetKeyEncryptionAlgorithm() string {
	if x != nil {
		return x.KeyEncryptionAlgorithm
	}
	return ""
}

func (x *EncryptionMetadata) GetNonceOrIv() []byte {
	if x != nil {
		return x.NonceOrIv
	}
	return nil
}

func (x *EncryptionMetadata) GetAdditionalAuthenticatedData() map[string]string {
	if x != nil {
		return x.AdditionalAuthenticatedData
	}
	return nil
}

type ShardingPolicy struct {
	state                           protoimpl.MessageState           `protogen:"open.v1"`
	Algorithm                       ShardingPolicy_ShardingAlgorithm `protobuf:"varint,1,opt,name=algorithm,proto3,enum=blackice.v1.ShardingPolicy_ShardingAlgorithm" json:"algorithm,omitempty"`
	TotalShards                     int32                            `protobuf:"varint,2,opt,name=total_shards,json=totalShards,proto3" json:"total_shards,omitempty"`                                                                                                  // k+m for Reed-Solomon, n for Shamir
	RequiredShardsForReconstruction int32                            `protobuf:"varint,3,opt,name=required_shards_for_reconstruction,json=requiredShardsForReconstruction,proto3" json:"required_shards_for_reconstruction,omitempty"`                                  // k for Reed-Solomon, t for Shamir
	AlgorithmParameters             map[string]string                `protobuf:"bytes,4,rep,name=algorithm_parameters,json=algorithmParameters,proto3" json:"algorithm_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., polynomial details for Shamir
	PlacementPolicyId               string                           `protobuf:"bytes,5,opt,name=placement_policy_id,json=placementPolicyId,proto3" json:"placement_policy_id,omitempty"`                                                                               // Defines geographic/provider distribution rules
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ShardingPolicy) Reset() {
	*x = ShardingPolicy{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardingPolicy) ProtoMessage() {}

func (x *ShardingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardingPolicy.ProtoReflect.Descriptor instead.
func (*ShardingPolicy) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{3}
}

func (x *ShardingPolicy) GetAlgorithm() ShardingPolicy_ShardingAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return ShardingPolicy_REED_SOLOMON
}

func (x *ShardingPolicy) GetTotalShards() int32 {
	if x != nil {
		return x.TotalShards
	}
	return 0
}

func (x *ShardingPolicy) GetRequiredShardsForReconstruction() int32 {
	if x != nil {
		return x.RequiredShardsForReconstruction
	}
	return 0
}

func (x *ShardingPolicy) GetAlgorithmParameters() map[string]string {
	if x != nil {
		return x.AlgorithmParameters
	}
	return nil
}

func (x *ShardingPolicy) GetPlacementPolicyId() string {
	if x != nil {
		return x.PlacementPolicyId
	}
	return ""
}

type StoreObjectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ObjectId        string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`                        // Client can suggest, server may override or append unique suffix
	ObjectDataChunk []byte                 `protobuf:"bytes,2,opt,name=object_data_chunk,json=objectDataChunk,proto3" json:"object_data_chunk,omitempty"` // Streamed if object is large, or single chunk for small objects
	// For streamed requests:
	SequenceNumber         int64             `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	IsLastChunk            bool              `protobuf:"varint,4,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	TotalObjectSizeBytes   int64             `protobuf:"varint,5,opt,name=total_object_size_bytes,json=totalObjectSizeBytes,proto3" json:"total_object_size_bytes,omitempty"` // If known upfront
	ContentType            string            `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	UserMetadata           map[string]string `protobuf:"bytes,7,rep,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShardingPolicyOverride *ShardingPolicy   `protobuf:"bytes,8,opt,name=sharding_policy_override,json=shardingPolicyOverride,proto3" json:"sharding_policy_override,omitempty"` // Optional: override default policy
	ClientAttestation      *Attestation      `protobuf:"bytes,9,opt,name=client_attestation,json=clientAttestation,proto3" json:"client_attestation,omitempty"`                  // Attestation of the data from the client
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StoreObjectRequest) Reset() {
	*x = StoreObjectRequest{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreObjectRequest) ProtoMessage() {}

func (x *StoreObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreObjectRequest.ProtoReflect.Descriptor instead.
func (*StoreObjectRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{4}
}

func (x *StoreObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *StoreObjectRequest) GetObjectDataChunk() []byte {
	if x != nil {
		return x.ObjectDataChunk
	}
	return nil
}

func (x *StoreObjectRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *StoreObjectRequest) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *StoreObjectRequest) GetTotalObjectSizeBytes() int64 {
	if x != nil {
		return x.TotalObjectSizeBytes
	}
	return 0
}

func (x *StoreObjectRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *StoreObjectRequest) GetUserMetadata() map[string]string {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *StoreObjectRequest) GetShardingPolicyOverride() *ShardingPolicy {
	if x != nil {
		return x.ShardingPolicyOverride
	}
	return nil
}

func (x *StoreObjectRequest) GetClientAttestation() *Attestation {
	if x != nil {
		return x.ClientAttestation
	}
	return nil
}

type StoreObjectResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ObjectId                string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	MetadataConfirmation    *ObjectMetadata        `protobuf:"bytes,3,opt,name=metadata_confirmation,json=metadataConfirmation,proto3" json:"metadata_confirmation,omitempty"`
	LedgerEntryConfirmation *LedgerEntry           `protobuf:"bytes,4,opt,name=ledger_entry_confirmation,json=ledgerEntryConfirmation,proto3" json:"ledger_entry_confirmation,omitempty"`
	CompletedAtUnixNs       int64                  `protobuf:"varint,5,opt,name=completed_at_unix_ns,json=completedAtUnixNs,proto3" json:"completed_at_unix_ns,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StoreObjectResponse) Reset() {
	*x = StoreObjectResponse{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreObjectResponse) ProtoMessage() {}

func (x *StoreObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreObjectResponse.ProtoReflect.Descriptor instead.
func (*StoreObjectResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{5}
}

func (x *StoreObjectResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StoreObjectResponse) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *StoreObjectResponse) GetMetadataConfirmation() *ObjectMetadata {
	if x != nil {
		return x.MetadataConfirmation
	}
	return nil
}

func (x *StoreObjectResponse) GetLedgerEntryConfirmation() *LedgerEntry {
	if x != nil {
		return x.LedgerEntryConfirmation
	}
	return nil
}

func (x *StoreObjectResponse) GetCompletedAtUnixNs() int64 {
	if x != nil {
		return x.CompletedAtUnixNs
	}
	return 0
}

type RetrieveObjectRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ObjectId string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// Optional: specify specific shards to use or avoid, for advanced recovery scenarios
	PreferredShardIds     []string `protobuf:"bytes,2,rep,name=preferred_shard_ids,json=preferredShardIds,proto3" json:"preferred_shard_ids,omitempty"`
	ExcludedShardIds      []string `protobuf:"bytes,3,rep,name=excluded_shard_ids,json=excludedShardIds,proto3" json:"excluded_shard_ids,omitempty"`
	DesiredChunkSizeBytes int32    `protobuf:"varint,4,opt,name=desired_chunk_size_bytes,json=desiredChunkSizeBytes,proto3" json:"desired_chunk_size_bytes,omitempty"` // How large each ObjectChunk payload should be
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RetrieveObjectRequest) Reset() {
	*x = RetrieveObjectRequest{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveObjectRequest) ProtoMessage() {}

func (x *RetrieveObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveObjectRequest.ProtoReflect.Descriptor instead.
func (*RetrieveObjectRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{6}
}

func (x *RetrieveObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RetrieveObjectRequest) GetPreferredShardIds() []string {
	if x != nil {
		return x.PreferredShardIds
	}
	return nil
}

func (x *RetrieveObjectRequest) GetExcludedShardIds() []string {
	if x != nil {
		return x.ExcludedShardIds
	}
	return nil
}

func (x *RetrieveObjectRequest) GetDesiredChunkSizeBytes() int32 {
	if x != nil {
		return x.DesiredChunkSizeBytes
	}
	return 0
}

type ObjectChunk struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	DataChunk                 []byte                 `protobuf:"bytes,1,opt,name=data_chunk,json=dataChunk,proto3" json:"data_chunk,omitempty"`
	SequenceNumber            int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	IsLastChunk               bool                   `protobuf:"varint,3,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	Status                    *Status                `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                                                                          // Status for this chunk, e.g., if reconstruction errors occur mid-stream
	ChunkIntegrityAttestation *Attestation           `protobuf:"bytes,5,opt,name=chunk_integrity_attestation,json=chunkIntegrityAttestation,proto3" json:"chunk_integrity_attestation,omitempty"` // Attestation of this reconstructed chunk
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ObjectChunk) Reset() {
	*x = ObjectChunk{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectChunk) ProtoMessage() {}

func (x *ObjectChunk) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectChunk.ProtoReflect.Descriptor instead.
func (*ObjectChunk) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{7}
}

func (x *ObjectChunk) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

func (x *ObjectChunk) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ObjectChunk) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

func (x *ObjectChunk) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ObjectChunk) GetChunkIntegrityAttestation() *Attestation {
	if x != nil {
		return x.ChunkIntegrityAttestation
	}
	return nil
}

type DeleteObjectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectId         string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	AdminAttestation *Attestation           `protobuf:"bytes,2,opt,name=admin_attestation,json=adminAttestation,proto3" json:"admin_attestation,omitempty"` // Authorization for deletion
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ImmediateShred   bool                   `protobuf:"varint,4,opt,name=immediate_shred,json=immediateShred,proto3" json:"immediate_shred,omitempty"` // If true, attempt to securely shred shards immediately vs. grace period
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DeleteObjectRequest) GetAdminAttestation() *Attestation {
	if x != nil {
		return x.AdminAttestation
	}
	return nil
}

func (x *DeleteObjectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DeleteObjectRequest) GetImmediateShred() bool {
	if x != nil {
		return x.ImmediateShred
	}
	return false
}

type ResilienceOperationResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	OperationId             string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CompletedAtUnixNs       int64                  `protobuf:"varint,3,opt,name=completed_at_unix_ns,json=completedAtUnixNs,proto3" json:"completed_at_unix_ns,omitempty"`
	LedgerEntryConfirmation *LedgerEntry           `protobuf:"bytes,4,opt,name=ledger_entry_confirmation,json=ledgerEntryConfirmation,proto3" json:"ledger_entry_confirmation,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResilienceOperationResponse) Reset() {
	*x = ResilienceOperationResponse{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResilienceOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResilienceOperationResponse) ProtoMessage() {}

func (x *ResilienceOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResilienceOperationResponse.ProtoReflect.Descriptor instead.
func (*ResilienceOperationResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{9}
}

func (x *ResilienceOperationResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ResilienceOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ResilienceOperationResponse) GetCompletedAtUnixNs() int64 {
	if x != nil {
		return x.CompletedAtUnixNs
	}
	return 0
}

func (x *ResilienceOperationResponse) GetLedgerEntryConfirmation() *LedgerEntry {
	if x != nil {
		return x.LedgerEntryConfirmation
	}
	return nil
}

type GetObjectStatusRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ObjectId            string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	IncludeShardDetails bool                   `protobuf:"varint,2,opt,name=include_shard_details,json=includeShardDetails,proto3" json:"include_shard_details,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetObjectStatusRequest) Reset() {
	*x = GetObjectStatusRequest{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectStatusRequest) ProtoMessage() {}

func (x *GetObjectStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectStatusRequest.ProtoReflect.Descriptor instead.
func (*GetObjectStatusRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{10}
}

func (x *GetObjectStatusRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetObjectStatusRequest) GetIncludeShardDetails() bool {
	if x != nil {
		return x.IncludeShardDetails
	}
	return false
}

type GetObjectStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *ObjectMetadata        `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectStatusResponse) Reset() {
	*x = GetObjectStatusResponse{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectStatusResponse) ProtoMessage() {}

func (x *GetObjectStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectStatusResponse.ProtoReflect.Descriptor instead.
func (*GetObjectStatusResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{11}
}

func (x *GetObjectStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetObjectStatusResponse) GetMetadata() *ObjectMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RepairObjectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObjectId         string                 `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	AdminAttestation *Attestation           `protobuf:"bytes,2,opt,name=admin_attestation,json=adminAttestation,proto3" json:"admin_attestation,omitempty"` // Authorization for repair (may involve cost/resource use)
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional: specify a sharding policy to migrate to during repair
	TargetShardingPolicy *ShardingPolicy `protobuf:"bytes,4,opt,name=target_sharding_policy,json=targetShardingPolicy,proto3" json:"target_sharding_policy,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RepairObjectRequest) Reset() {
	*x = RepairObjectRequest{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepairObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepairObjectRequest) ProtoMessage() {}

func (x *RepairObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepairObjectRequest.ProtoReflect.Descriptor instead.
func (*RepairObjectRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{12}
}

func (x *RepairObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *RepairObjectRequest) GetAdminAttestation() *Attestation {
	if x != nil {
		return x.AdminAttestation
	}
	return nil
}

func (x *RepairObjectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RepairObjectRequest) GetTargetShardingPolicy() *ShardingPolicy {
	if x != nil {
		return x.TargetShardingPolicy
	}
	return nil
}

type UpdatePlacementPolicyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PolicyId         string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"` // New or existing policy ID
	PolicyDefinition *PlacementPolicy       `protobuf:"bytes,2,opt,name=policy_definition,json=policyDefinition,proto3" json:"policy_definition,omitempty"`
	AdminAttestation *Attestation           `protobuf:"bytes,3,opt,name=admin_attestation,json=adminAttestation,proto3" json:"admin_attestation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdatePlacementPolicyRequest) Reset() {
	*x = UpdatePlacementPolicyRequest{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlacementPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlacementPolicyRequest) ProtoMessage() {}

func (x *UpdatePlacementPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlacementPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlacementPolicyRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{13}
}

func (x *UpdatePlacementPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UpdatePlacementPolicyRequest) GetPolicyDefinition() *PlacementPolicy {
	if x != nil {
		return x.PolicyDefinition
	}
	return nil
}

func (x *UpdatePlacementPolicyRequest) GetAdminAttestation() *Attestation {
	if x != nil {
		return x.AdminAttestation
	}
	return nil
}

type PlacementPolicy struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	PolicyId           string                   `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Description        string                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Rules              []*PlacementRule         `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	Strategy           PlacementPolicy_Strategy `protobuf:"varint,4,opt,name=strategy,proto3,enum=blackice.v1.PlacementPolicy_Strategy" json:"strategy,omitempty"`
	StrategyParameters map[string]string        `protobuf:"bytes,5,rep,name=strategy_parameters,json=strategyParameters,proto3" json:"strategy_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PlacementPolicy) Reset() {
	*x = PlacementPolicy{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementPolicy) ProtoMessage() {}

func (x *PlacementPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementPolicy.ProtoReflect.Descriptor instead.
func (*PlacementPolicy) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{14}
}

func (x *PlacementPolicy) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PlacementPolicy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlacementPolicy) GetRules() []*PlacementRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *PlacementPolicy) GetStrategy() PlacementPolicy_Strategy {
	if x != nil {
		return x.Strategy
	}
	return PlacementPolicy_GEO_DIVERSE_REGIONS
}

func (x *PlacementPolicy) GetStrategyParameters() map[string]string {
	if x != nil {
		return x.StrategyParameters
	}
	return nil
}

type PlacementRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g., require_min_shards_in_region["US-EAST"] = 2
	// e.g., exclude_providers = ["AWS", "GCP"]
	Conditions     map[string]string `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MinShardsMatch int32             `protobuf:"varint,2,opt,name=min_shards_match,json=minShardsMatch,proto3" json:"min_shards_match,omitempty"`
	MaxShardsMatch int32             `protobuf:"varint,3,opt,name=max_shards_match,json=maxShardsMatch,proto3" json:"max_shards_match,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlacementRule) Reset() {
	*x = PlacementRule{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementRule) ProtoMessage() {}

func (x *PlacementRule) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementRule.ProtoReflect.Descriptor instead.
func (*PlacementRule) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{15}
}

func (x *PlacementRule) GetConditions() map[string]string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *PlacementRule) GetMinShardsMatch() int32 {
	if x != nil {
		return x.MinShardsMatch
	}
	return 0
}

func (x *PlacementRule) GetMaxShardsMatch() int32 {
	if x != nil {
		return x.MaxShardsMatch
	}
	return 0
}

type StorageNodeHealthRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                         // Specific node ID to query
	ProviderFilter     string                 `protobuf:"bytes,2,opt,name=provider_filter,json=providerFilter,proto3" json:"provider_filter,omitempty"` // e.g., "Storj", "IPFS"
	OnlyUnhealthyNodes bool                   `protobuf:"varint,3,opt,name=only_unhealthy_nodes,json=onlyUnhealthyNodes,proto3" json:"only_unhealthy_nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StorageNodeHealthRequest) Reset() {
	*x = StorageNodeHealthRequest{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageNodeHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageNodeHealthRequest) ProtoMessage() {}

func (x *StorageNodeHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageNodeHealthRequest.ProtoReflect.Descriptor instead.
func (*StorageNodeHealthRequest) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{16}
}

func (x *StorageNodeHealthRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StorageNodeHealthRequest) GetProviderFilter() string {
	if x != nil {
		return x.ProviderFilter
	}
	return ""
}

func (x *StorageNodeHealthRequest) GetOnlyUnhealthyNodes() bool {
	if x != nil {
		return x.OnlyUnhealthyNodes
	}
	return false
}

type StorageNodeHealthResponse struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	Status               *Status                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeHealthDetails    []*NodeHealth             `protobuf:"bytes,2,rep,name=node_health_details,json=nodeHealthDetails,proto3" json:"node_health_details,omitempty"`
	ProviderSummaryStats map[string]*ProviderStats `protobuf:"bytes,3,rep,name=provider_summary_stats,json=providerSummaryStats,proto3" json:"provider_summary_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StorageNodeHealthResponse) Reset() {
	*x = StorageNodeHealthResponse{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageNodeHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageNodeHealthResponse) ProtoMessage() {}

func (x *StorageNodeHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageNodeHealthResponse.ProtoReflect.Descriptor instead.
func (*StorageNodeHealthResponse) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{17}
}

func (x *StorageNodeHealthResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *StorageNodeHealthResponse) GetNodeHealthDetails() []*NodeHealth {
	if x != nil {
		return x.NodeHealthDetails
	}
	return nil
}

func (x *StorageNodeHealthResponse) GetProviderSummaryStats() map[string]*ProviderStats {
	if x != nil {
		return x.ProviderSummaryStats
	}
	return nil
}

type ProviderStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProviderName       string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	TotalNodes         int32                  `protobuf:"varint,2,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	HealthyNodes       int32                  `protobuf:"varint,3,opt,name=healthy_nodes,json=healthyNodes,proto3" json:"healthy_nodes,omitempty"`
	TotalCapacityBytes int64                  `protobuf:"varint,4,opt,name=total_capacity_bytes,json=totalCapacityBytes,proto3" json:"total_capacity_bytes,omitempty"`
	UsedCapacityBytes  int64                  `protobuf:"varint,5,opt,name=used_capacity_bytes,json=usedCapacityBytes,proto3" json:"used_capacity_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProviderStats) Reset() {
	*x = ProviderStats{}
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderStats) ProtoMessage() {}

func (x *ProviderStats) ProtoReflect() protoreflect.Message {
	mi := &file_blackice_proto_blackice_v1_resilience_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderStats.ProtoReflect.Descriptor instead.
func (*ProviderStats) Descriptor() ([]byte, []int) {
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP(), []int{18}
}

func (x *ProviderStats) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProviderStats) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *ProviderStats) GetHealthyNodes() int32 {
	if x != nil {
		return x.HealthyNodes
	}
	return 0
}

func (x *ProviderStats) GetTotalCapacityBytes() int64 {
	if x != nil {
		return x.TotalCapacityBytes
	}
	return 0
}

func (x *ProviderStats) GetUsedCapacityBytes() int64 {
	if x != nil {
		return x.UsedCapacityBytes
	}
	return 0
}

var File_blackice_proto_blackice_v1_resilience_proto protoreflect.FileDescriptor

const file_blackice_proto_blackice_v1_resilience_proto_rawDesc = "" +
	"\n" +
	"+blackice/proto/blackice/v1/resilience.proto\x12\vblackice.v1\x1a'blackice/proto/blackice/v1/common.proto\"\xfc\x03\n" +
	"\rShardMetadata\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12&\n" +
	"\x0fstorage_node_id\x18\x02 \x01(\tR\rstorageNodeId\x12)\n" +
	"\x10storage_provider\x18\x03 \x01(\tR\x0fstorageProvider\x12.\n" +
	"\x13shard_location_hint\x18\x04 \x01(\tR\x11shardLocationHint\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12M\n" +
	"\x15integrity_attestation\x18\x06 \x01(\v2\x18.blackice.v1.AttestationR\x14integrityAttestation\x12)\n" +
	"\x11stored_at_unix_ns\x18\a \x01(\x03R\x0estoredAtUnixNs\x12Q\n" +
	"\rhealth_status\x18\b \x01(\x0e2,.blackice.v1.ShardMetadata.ShardHealthStatusR\fhealthStatus\"a\n" +
	"\x11ShardHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\x0f\n" +
	"\vUNREACHABLE\x10\x02\x12\r\n" +
	"\tCORRUPTED\x10\x03\x12\x12\n" +
	"\x0ePENDING_REPAIR\x10\x04\"\xb4\a\n" +
	"\x0eObjectMetadata\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12.\n" +
	"\x13original_size_bytes\x18\x02 \x01(\x03R\x11originalSizeBytes\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12R\n" +
	"\ruser_metadata\x18\x04 \x03(\v2-.blackice.v1.ObjectMetadata.UserMetadataEntryR\fuserMetadata\x12P\n" +
	"\x13encryption_metadata\x18\x05 \x01(\v2\x1f.blackice.v1.EncryptionMetadataR\x12encryptionMetadata\x12M\n" +
	"\x14sharding_policy_used\x18\x06 \x01(\v2\x1b.blackice.v1.ShardingPolicyR\x12shardingPolicyUsed\x122\n" +
	"\x06shards\x18\a \x03(\v2\x1a.blackice.v1.ShardMetadataR\x06shards\x12+\n" +
	"\x12created_at_unix_ns\x18\b \x01(\x03R\x0fcreatedAtUnixNs\x121\n" +
	"\x15last_accessed_unix_ns\x18\t \x01(\x03R\x12lastAccessedUnixNs\x126\n" +
	"\x18last_repaired_at_unix_ns\x18\n" +
	" \x01(\x03R\x14lastRepairedAtUnixNs\x12X\n" +
	"\x1bobject_creation_attestation\x18\v \x01(\v2\x18.blackice.v1.AttestationR\x19objectCreationAttestation\x12U\n" +
	"\x0eoverall_health\x18\f \x01(\x0e2..blackice.v1.ObjectMetadata.ObjectHealthStatusR\roverallHealth\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x12ObjectHealthStatus\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEALTH_OPTIMAL\x10\x01\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x02\x12\x12\n" +
	"\x0eHEALTH_AT_RISK\x10\x03\x12\x18\n" +
	"\x14HEALTH_UNRECOVERABLE\x10\x04\"\x97\x03\n" +
	"\x12EncryptionMetadata\x12\"\n" +
	"\rmaster_key_id\x18\x01 \x01(\tR\vmasterKeyId\x12,\n" +
	"\x12encrypted_data_key\x18\x02 \x01(\fR\x10encryptedDataKey\x128\n" +
	"\x18key_encryption_algorithm\x18\x03 \x01(\tR\x16keyEncryptionAlgorithm\x12\x1e\n" +
	"\vnonce_or_iv\x18\x04 \x01(\fR\tnonceOrIv\x12\x84\x01\n" +
	"\x1dadditional_authenticated_data\x18\x05 \x03(\v2@.blackice.v1.EncryptionMetadata.AdditionalAuthenticatedDataEntryR\x1badditionalAuthenticatedData\x1aN\n" +
	" AdditionalAuthenticatedDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x04\n" +
	"\x0eShardingPolicy\x12K\n" +
	"\talgorithm\x18\x01 \x01(\x0e2-.blackice.v1.ShardingPolicy.ShardingAlgorithmR\talgorithm\x12!\n" +
	"\ftotal_shards\x18\x02 \x01(\x05R\vtotalShards\x12K\n" +
	"\"required_shards_for_reconstruction\x18\x03 \x01(\x05R\x1frequiredShardsForReconstruction\x12g\n" +
	"\x14algorithm_parameters\x18\x04 \x03(\v24.blackice.v1.ShardingPolicy.AlgorithmParametersEntryR\x13algorithmParameters\x12.\n" +
	"\x13placement_policy_id\x18\x05 \x01(\tR\x11placementPolicyId\x1aF\n" +
	"\x18AlgorithmParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x11ShardingAlgorithm\x12\x10\n" +
	"\fREED_SOLOMON\x10\x00\x12\x19\n" +
	"\x15SHAMIR_SECRET_SHARING\x10\x01\x12\x1e\n" +
	"\x1aHYBRID_REED_SOLOMON_SHAMIR\x10\x02\"\xbd\x04\n" +
	"\x12StoreObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12*\n" +
	"\x11object_data_chunk\x18\x02 \x01(\fR\x0fobjectDataChunk\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\x12\"\n" +
	"\ris_last_chunk\x18\x04 \x01(\bR\visLastChunk\x125\n" +
	"\x17total_object_size_bytes\x18\x05 \x01(\x03R\x14totalObjectSizeBytes\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12V\n" +
	"\ruser_metadata\x18\a \x03(\v21.blackice.v1.StoreObjectRequest.UserMetadataEntryR\fuserMetadata\x12U\n" +
	"\x18sharding_policy_override\x18\b \x01(\v2\x1b.blackice.v1.ShardingPolicyR\x16shardingPolicyOverride\x12G\n" +
	"\x12client_attestation\x18\t \x01(\v2\x18.blackice.v1.AttestationR\x11clientAttestation\x1a?\n" +
	"\x11UserMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x02\n" +
	"\x13StoreObjectResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12P\n" +
	"\x15metadata_confirmation\x18\x03 \x01(\v2\x1b.blackice.v1.ObjectMetadataR\x14metadataConfirmation\x12T\n" +
	"\x19ledger_entry_confirmation\x18\x04 \x01(\v2\x18.blackice.v1.LedgerEntryR\x17ledgerEntryConfirmation\x12/\n" +
	"\x14completed_at_unix_ns\x18\x05 \x01(\x03R\x11completedAtUnixNs\"\xcb\x01\n" +
	"\x15RetrieveObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12.\n" +
	"\x13preferred_shard_ids\x18\x02 \x03(\tR\x11preferredShardIds\x12,\n" +
	"\x12excluded_shard_ids\x18\x03 \x03(\tR\x10excludedShardIds\x127\n" +
	"\x18desired_chunk_size_bytes\x18\x04 \x01(\x05R\x15desiredChunkSizeBytes\"\x80\x02\n" +
	"\vObjectChunk\x12\x1d\n" +
	"\n" +
	"data_chunk\x18\x01 \x01(\fR\tdataChunk\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x12\"\n" +
	"\ris_last_chunk\x18\x03 \x01(\bR\visLastChunk\x12+\n" +
	"\x06status\x18\x04 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12X\n" +
	"\x1bchunk_integrity_attestation\x18\x05 \x01(\v2\x18.blackice.v1.AttestationR\x19chunkIntegrityAttestation\"\xba\x01\n" +
	"\x13DeleteObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12E\n" +
	"\x11admin_attestation\x18\x02 \x01(\v2\x18.blackice.v1.AttestationR\x10adminAttestation\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12'\n" +
	"\x0fimmediate_shred\x18\x04 \x01(\bR\x0eimmediateShred\"\xf4\x01\n" +
	"\x1bResilienceOperationResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\x12/\n" +
	"\x14completed_at_unix_ns\x18\x03 \x01(\x03R\x11completedAtUnixNs\x12T\n" +
	"\x19ledger_entry_confirmation\x18\x04 \x01(\v2\x18.blackice.v1.LedgerEntryR\x17ledgerEntryConfirmation\"i\n" +
	"\x16GetObjectStatusRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x122\n" +
	"\x15include_shard_details\x18\x02 \x01(\bR\x13includeShardDetails\"\x7f\n" +
	"\x17GetObjectStatusResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.blackice.v1.ObjectMetadataR\bmetadata\"\xe4\x01\n" +
	"\x13RepairObjectRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\tR\bobjectId\x12E\n" +
	"\x11admin_attestation\x18\x02 \x01(\v2\x18.blackice.v1.AttestationR\x10adminAttestation\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12Q\n" +
	"\x16target_sharding_policy\x18\x04 \x01(\v2\x1b.blackice.v1.ShardingPolicyR\x14targetShardingPolicy\"\xcd\x01\n" +
	"\x1cUpdatePlacementPolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12I\n" +
	"\x11policy_definition\x18\x02 \x01(\v2\x1c.blackice.v1.PlacementPolicyR\x10policyDefinition\x12E\n" +
	"\x11admin_attestation\x18\x03 \x01(\v2\x18.blackice.v1.AttestationR\x10adminAttestation\"\xc6\x03\n" +
	"\x0fPlacementPolicy\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x05rules\x18\x03 \x03(\v2\x1a.blackice.v1.PlacementRuleR\x05rules\x12A\n" +
	"\bstrategy\x18\x04 \x01(\x0e2%.blackice.v1.PlacementPolicy.StrategyR\bstrategy\x12e\n" +
	"\x13strategy_parameters\x18\x05 \x03(\v24.blackice.v1.PlacementPolicy.StrategyParametersEntryR\x12strategyParameters\x1aE\n" +
	"\x17StrategyParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\bStrategy\x12\x17\n" +
	"\x13GEO_DIVERSE_REGIONS\x10\x00\x12\x14\n" +
	"\x10PROVIDER_DIVERSE\x10\x01\x12\x16\n" +
	"\x12LOW_LATENCY_ACCESS\x10\x02\"\xee\x01\n" +
	"\rPlacementRule\x12J\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2*.blackice.v1.PlacementRule.ConditionsEntryR\n" +
	"conditions\x12(\n" +
	"\x10min_shards_match\x18\x02 \x01(\x05R\x0eminShardsMatch\x12(\n" +
	"\x10max_shards_match\x18\x03 \x01(\x05R\x0emaxShardsMatch\x1a=\n" +
	"\x0fConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x18StorageNodeHealthRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fprovider_filter\x18\x02 \x01(\tR\x0eproviderFilter\x120\n" +
	"\x14only_unhealthy_nodes\x18\x03 \x01(\bR\x12onlyUnhealthyNodes\"\xee\x02\n" +
	"\x19StorageNodeHealthResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.blackice.v1.StatusR\x06status\x12G\n" +
	"\x13node_health_details\x18\x02 \x03(\v2\x17.blackice.v1.NodeHealthR\x11nodeHealthDetails\x12v\n" +
	"\x16provider_summary_stats\x18\x03 \x03(\v2@.blackice.v1.StorageNodeHealthResponse.ProviderSummaryStatsEntryR\x14providerSummaryStats\x1ac\n" +
	"\x19ProviderSummaryStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.blackice.v1.ProviderStatsR\x05value:\x028\x01\"\xdc\x01\n" +
	"\rProviderStats\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x1f\n" +
	"\vtotal_nodes\x18\x02 \x01(\x05R\n" +
	"totalNodes\x12#\n" +
	"\rhealthy_nodes\x18\x03 \x01(\x05R\fhealthyNodes\x120\n" +
	"\x14total_capacity_bytes\x18\x04 \x01(\x03R\x12totalCapacityBytes\x12.\n" +
	"\x13used_capacity_bytes\x18\x05 \x01(\x03R\x11usedCapacityBytes2\xa8\x05\n" +
	"\x11ResilienceService\x12P\n" +
	"\vStoreObject\x12\x1f.blackice.v1.StoreObjectRequest\x1a .blackice.v1.StoreObjectResponse\x12P\n" +
	"\x0eRetrieveObject\x12\".blackice.v1.RetrieveObjectRequest\x1a\x18.blackice.v1.ObjectChunk0\x01\x12Z\n" +
	"\fDeleteObject\x12 .blackice.v1.DeleteObjectRequest\x1a(.blackice.v1.ResilienceOperationResponse\x12\\\n" +
	"\x0fGetObjectStatus\x12#.blackice.v1.GetObjectStatusRequest\x1a$.blackice.v1.GetObjectStatusResponse\x12Z\n" +
	"\fRepairObject\x12 .blackice.v1.RepairObjectRequest\x1a(.blackice.v1.ResilienceOperationResponse\x12r\n" +
	"\x1bUpdateObjectPlacementPolicy\x12).blackice.v1.UpdatePlacementPolicyRequest\x1a(.blackice.v1.ResilienceOperationResponse\x12e\n" +
	"\x14GetStorageNodeHealth\x12%.blackice.v1.StorageNodeHealthRequest\x1a&.blackice.v1.StorageNodeHealthResponseB7Z5github.com/TFMV/blackice/proto/blackice/v1;blackicev1b\x06proto3"

var (
	file_blackice_proto_blackice_v1_resilience_proto_rawDescOnce sync.Once
	file_blackice_proto_blackice_v1_resilience_proto_rawDescData []byte
)

func file_blackice_proto_blackice_v1_resilience_proto_rawDescGZIP() []byte {
	file_blackice_proto_blackice_v1_resilience_proto_rawDescOnce.Do(func() {
		file_blackice_proto_blackice_v1_resilience_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blackice_proto_blackice_v1_resilience_proto_rawDesc), len(file_blackice_proto_blackice_v1_resilience_proto_rawDesc)))
	})
	return file_blackice_proto_blackice_v1_resilience_proto_rawDescData
}

var file_blackice_proto_blackice_v1_resilience_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_blackice_proto_blackice_v1_resilience_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_blackice_proto_blackice_v1_resilience_proto_goTypes = []any{
	(ShardMetadata_ShardHealthStatus)(0),   // 0: blackice.v1.ShardMetadata.ShardHealthStatus
	(ObjectMetadata_ObjectHealthStatus)(0), // 1: blackice.v1.ObjectMetadata.ObjectHealthStatus
	(ShardingPolicy_ShardingAlgorithm)(0),  // 2: blackice.v1.ShardingPolicy.ShardingAlgorithm
	(PlacementPolicy_Strategy)(0),          // 3: blackice.v1.PlacementPolicy.Strategy
	(*ShardMetadata)(nil),                  // 4: blackice.v1.ShardMetadata
	(*ObjectMetadata)(nil),                 // 5: blackice.v1.ObjectMetadata
	(*EncryptionMetadata)(nil),             // 6: blackice.v1.EncryptionMetadata
	(*ShardingPolicy)(nil),                 // 7: blackice.v1.ShardingPolicy
	(*StoreObjectRequest)(nil),             // 8: blackice.v1.StoreObjectRequest
	(*StoreObjectResponse)(nil),            // 9: blackice.v1.StoreObjectResponse
	(*RetrieveObjectRequest)(nil),          // 10: blackice.v1.RetrieveObjectRequest
	(*ObjectChunk)(nil),                    // 11: blackice.v1.ObjectChunk
	(*DeleteObjectRequest)(nil),            // 12: blackice.v1.DeleteObjectRequest
	(*ResilienceOperationResponse)(nil),    // 13: blackice.v1.ResilienceOperationResponse
	(*GetObjectStatusRequest)(nil),         // 14: blackice.v1.GetObjectStatusRequest
	(*GetObjectStatusResponse)(nil),        // 15: blackice.v1.GetObjectStatusResponse
	(*RepairObjectRequest)(nil),            // 16: blackice.v1.RepairObjectRequest
	(*UpdatePlacementPolicyRequest)(nil),   // 17: blackice.v1.UpdatePlacementPolicyRequest
	(*PlacementPolicy)(nil),                // 18: blackice.v1.PlacementPolicy
	(*PlacementRule)(nil),                  // 19: blackice.v1.PlacementRule
	(*StorageNodeHealthRequest)(nil),       // 20: blackice.v1.StorageNodeHealthRequest
	(*StorageNodeHealthResponse)(nil),      // 21: blackice.v1.StorageNodeHealthResponse
	(*ProviderStats)(nil),                  // 22: blackice.v1.ProviderStats
	nil,                                    // 23: blackice.v1.ObjectMetadata.UserMetadataEntry
	nil,                                    // 24: blackice.v1.EncryptionMetadata.AdditionalAuthenticatedDataEntry
	nil,                                    // 25: blackice.v1.ShardingPolicy.AlgorithmParametersEntry
	nil,                                    // 26: blackice.v1.StoreObjectRequest.UserMetadataEntry
	nil,                                    // 27: blackice.v1.PlacementPolicy.StrategyParametersEntry
	nil,                                    // 28: blackice.v1.PlacementRule.ConditionsEntry
	nil,                                    // 29: blackice.v1.StorageNodeHealthResponse.ProviderSummaryStatsEntry
	(*Attestation)(nil),                    // 30: blackice.v1.Attestation
	(*Status)(nil),                         // 31: blackice.v1.Status
	(*LedgerEntry)(nil),                    // 32: blackice.v1.LedgerEntry
	(*NodeHealth)(nil),                     // 33: blackice.v1.NodeHealth
}
var file_blackice_proto_blackice_v1_resilience_proto_depIdxs = []int32{
	30, // 0: blackice.v1.ShardMetadata.integrity_attestation:type_name -> blackice.v1.Attestation
	0,  // 1: blackice.v1.ShardMetadata.health_status:type_name -> blackice.v1.ShardMetadata.ShardHealthStatus
	23, // 2: blackice.v1.ObjectMetadata.user_metadata:type_name -> blackice.v1.ObjectMetadata.UserMetadataEntry
	6,  // 3: blackice.v1.ObjectMetadata.encryption_metadata:type_name -> blackice.v1.EncryptionMetadata
	7,  // 4: blackice.v1.ObjectMetadata.sharding_policy_used:type_name -> blackice.v1.ShardingPolicy
	4,  // 5: blackice.v1.ObjectMetadata.shards:type_name -> blackice.v1.ShardMetadata
	30, // 6: blackice.v1.ObjectMetadata.object_creation_attestation:type_name -> blackice.v1.Attestation
	1,  // 7: blackice.v1.ObjectMetadata.overall_health:type_name -> blackice.v1.ObjectMetadata.ObjectHealthStatus
	24, // 8: blackice.v1.EncryptionMetadata.additional_authenticated_data:type_name -> blackice.v1.EncryptionMetadata.AdditionalAuthenticatedDataEntry
	2,  // 9: blackice.v1.ShardingPolicy.algorithm:type_name -> blackice.v1.ShardingPolicy.ShardingAlgorithm
	25, // 10: blackice.v1.ShardingPolicy.algorithm_parameters:type_name -> blackice.v1.ShardingPolicy.AlgorithmParametersEntry
	26, // 11: blackice.v1.StoreObjectRequest.user_metadata:type_name -> blackice.v1.StoreObjectRequest.UserMetadataEntry
	7,  // 12: blackice.v1.StoreObjectRequest.sharding_policy_override:type_name -> blackice.v1.ShardingPolicy
	30, // 13: blackice.v1.StoreObjectRequest.client_attestation:type_name -> blackice.v1.Attestation
	31, // 14: blackice.v1.StoreObjectResponse.status:type_name -> blackice.v1.Status
	5,  // 15: blackice.v1.StoreObjectResponse.metadata_confirmation:type_name -> blackice.v1.ObjectMetadata
	32, // 16: blackice.v1.StoreObjectResponse.ledger_entry_confirmation:type_name -> blackice.v1.LedgerEntry
	31, // 17: blackice.v1.ObjectChunk.status:type_name -> blackice.v1.Status
	30, // 18: blackice.v1.ObjectChunk.chunk_integrity_attestation:type_name -> blackice.v1.Attestation
	30, // 19: blackice.v1.DeleteObjectRequest.admin_attestation:type_name -> blackice.v1.Attestation
	31, // 20: blackice.v1.ResilienceOperationResponse.status:type_name -> blackice.v1.Status
	32, // 21: blackice.v1.ResilienceOperationResponse.ledger_entry_confirmation:type_name -> blackice.v1.LedgerEntry
	31, // 22: blackice.v1.GetObjectStatusResponse.status:type_name -> blackice.v1.Status
	5,  // 23: blackice.v1.GetObjectStatusResponse.metadata:type_name -> blackice.v1.ObjectMetadata
	30, // 24: blackice.v1.RepairObjectRequest.admin_attestation:type_name -> blackice.v1.Attestation
	7,  // 25: blackice.v1.RepairObjectRequest.target_sharding_policy:type_name -> blackice.v1.ShardingPolicy
	18, // 26: blackice.v1.UpdatePlacementPolicyRequest.policy_definition:type_name -> blackice.v1.PlacementPolicy
	30, // 27: blackice.v1.UpdatePlacementPolicyRequest.admin_attestation:type_name -> blackice.v1.Attestation
	19, // 28: blackice.v1.PlacementPolicy.rules:type_name -> blackice.v1.PlacementRule
	3,  // 29: blackice.v1.PlacementPolicy.strategy:type_name -> blackice.v1.PlacementPolicy.Strategy
	27, // 30: blackice.v1.PlacementPolicy.strategy_parameters:type_name -> blackice.v1.PlacementPolicy.StrategyParametersEntry
	28, // 31: blackice.v1.PlacementRule.conditions:type_name -> blackice.v1.PlacementRule.ConditionsEntry
	31, // 32: blackice.v1.StorageNodeHealthResponse.status:type_name -> blackice.v1.Status
	33, // 33: blackice.v1.StorageNodeHealthResponse.node_health_details:type_name -> blackice.v1.NodeHealth
	29, // 34: blackice.v1.StorageNodeHealthResponse.provider_summary_stats:type_name -> blackice.v1.StorageNodeHealthResponse.ProviderSummaryStatsEntry
	22, // 35: blackice.v1.StorageNodeHealthResponse.ProviderSummaryStatsEntry.value:type_name -> blackice.v1.ProviderStats
	8,  // 36: blackice.v1.ResilienceService.StoreObject:input_type -> blackice.v1.StoreObjectRequest
	10, // 37: blackice.v1.ResilienceService.RetrieveObject:input_type -> blackice.v1.RetrieveObjectRequest
	12, // 38: blackice.v1.ResilienceService.DeleteObject:input_type -> blackice.v1.DeleteObjectRequest
	14, // 39: blackice.v1.ResilienceService.GetObjectStatus:input_type -> blackice.v1.GetObjectStatusRequest
	16, // 40: blackice.v1.ResilienceService.RepairObject:input_type -> blackice.v1.RepairObjectRequest
	17, // 41: blackice.v1.ResilienceService.UpdateObjectPlacementPolicy:input_type -> blackice.v1.UpdatePlacementPolicyRequest
	20, // 42: blackice.v1.ResilienceService.GetStorageNodeHealth:input_type -> blackice.v1.StorageNodeHealthRequest
	9,  // 43: blackice.v1.ResilienceService.StoreObject:output_type -> blackice.v1.StoreObjectResponse
	11, // 44: blackice.v1.ResilienceService.RetrieveObject:output_type -> blackice.v1.ObjectChunk
	13, // 45: blackice.v1.ResilienceService.DeleteObject:output_type -> blackice.v1.ResilienceOperationResponse
	15, // 46: blackice.v1.ResilienceService.GetObjectStatus:output_type -> blackice.v1.GetObjectStatusResponse
	13, // 47: blackice.v1.ResilienceService.RepairObject:output_type -> blackice.v1.ResilienceOperationResponse
	13, // 48: blackice.v1.ResilienceService.UpdateObjectPlacementPolicy:output_type -> blackice.v1.ResilienceOperationResponse
	21, // 49: blackice.v1.ResilienceService.GetStorageNodeHealth:output_type -> blackice.v1.StorageNodeHealthResponse
	43, // [43:50] is the sub-list for method output_type
	36, // [36:43] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_blackice_proto_blackice_v1_resilience_proto_init() }
func file_blackice_proto_blackice_v1_resilience_proto_init() {
	if File_blackice_proto_blackice_v1_resilience_proto != nil {
		return
	}
	file_blackice_proto_blackice_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blackice_proto_blackice_v1_resilience_proto_rawDesc), len(file_blackice_proto_blackice_v1_resilience_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blackice_proto_blackice_v1_resilience_proto_goTypes,
		DependencyIndexes: file_blackice_proto_blackice_v1_resilience_proto_depIdxs,
		EnumInfos:         file_blackice_proto_blackice_v1_resilience_proto_enumTypes,
		MessageInfos:      file_blackice_proto_blackice_v1_resilience_proto_msgTypes,
	}.Build()
	File_blackice_proto_blackice_v1_resilience_proto = out.File
	file_blackice_proto_blackice_v1_resilience_proto_goTypes = nil
	file_blackice_proto_blackice_v1_resilience_proto_depIdxs = nil
}
